In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('apartamentos.csv')

## Cleaning

First we drop the index column which was carried over from `collect_data_realestate.py` because we didn't use `index=False` as an argument of `to_csv`.

In [3]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [4]:
df

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
0,\n\t\t\t\t\t\t\t\tR$ 4.700\n\t\t\t\t\t\t\t,\n\t\t+ R$ \n\t\t750 \n\t\tCondomínio\n\t,\n\t\t\t\t\t82 m²\n\t\t\t\t,"\n Chácara Santo Antônio, São Paulo\n",\n\t\t\t\t\t\t\t\t2 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t2\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,\n\t\t\t\t\t2\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n...,/imobiliarias/quintoandar_15743101-imoveis.html
1,\n\t\t\t\t\t\tR$ 3.720\n\t\t\t\t\t,\n\t\t+ R$ \n\t\t970 \n\t\tCondomínio\n\t,\n\t\t\t\t\t50 m²\n\t\t\t\t,"\n Vila Olímpia, São Paulo\n",\n\t\t\t\t\t\t\t\t1 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,NaN,/imobiliarias/quintoandar_15743101-imoveis.html
2,\n\t\t\t\t\t\tR$ 3.300\n\t\t\t\t\t,\n\t\t+ R$ \n\t\t443 \n\t\tCondomínio\n\t,\n\t\t\t\t\t85 m²\n\t\t\t\t,"\n Vila das Mercês, São Paulo\n",\n\t\t\t\t\t\t\t\t2 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t2\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tvaga\n\...,/imobiliarias/quintoandar_15743101-imoveis.html
3,\n\t\t\t\t\t\tR$ 1.250\n\t\t\t\t\t,\n\t\t+ R$ \n\t\t752 \n\t\tCondomínio\n\t,\n\t\t\t\t\t35 m²\n\t\t\t\t,"\n Vila Mascote, São Paulo\n",\n\t\t\t\t\t\t\t\t1 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tvaga\n\...,/imobiliarias/quintoandar_15743101-imoveis.html
4,\n\t\t\t\t\t\tR$ 2.835\n\t\t\t\t\t,\n\t\t+ R$ \n\t\t740 \n\t\tCondomínio\n\t,\n\t\t\t\t\t72 m²\n\t\t\t\t,"\n Saúde, São Paulo\n",\n\t\t\t\t\t\t\t\t3 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t2\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tvaga\n\...,/imobiliarias/quintoandar_15743101-imoveis.html
...,...,...,...,...,...,...,...,...
20731,\n\t\t\t\t\t\tR$ 2.100\n\t\t\t\t\t,\n\t\t+ R$ \n\t\t1.000 \n\t\tCondomínio\n\t,\n\t\t\t\t\t55 m²\n\t\t\t\t,"\n Vila Mariana, São Paulo\n",\n\t\t\t\t\t\t\t\t1 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tvaga\n\...,/imobiliarias/arbo-imoveis_47065316-imoveis.html
20732,\n\t\t\t\t\t\tR$ 1.500\n\t\t\t\t\t,\n\t\t+ R$ \n\t\t700 \n\t\tCondomínio\n\t,\n\t\t\t\t\t45 m²\n\t\t\t\t,"\n Moema, São Paulo\n",\n\t\t\t\t\t\t\t\t1 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tvaga\n\...,/imobiliarias/kramer_15765238-imoveis.html
20733,\n\t\t\t\t\t\tR$ 2.700\n\t\t\t\t\t,\n\t\t+ R$ \n\t\t560 \n\t\tCondomínio\n\t,\n\t\t\t\t\t58 m²\n\t\t\t\t,"\n Santa Cecília, São Paulo\n",\n\t\t\t\t\t\t\t\t2 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,NaN,/imobiliarias/c.t.sevi-venda-aluga-adm_1576592...
20734,\n\t\t\t\t\t\t\t\tR$ 1.000\n\t\t\t\t\t\t\t,\n\t\t+ R$ \n\t\t328 \n\t\tCondomínio\n\t,\n\t\t\t\t\t36 m²\n\t\t\t\t,"\n Bela Vista, São Paulo\n",\n\t\t\t\t\t\t\t\t1 dorm.\n\t\t\t\t\t\t\t,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t...,NaN,/imobiliarias/medeiros-negocios-imobiliarios-l...
20735,\n\t\t\t\t\t\tR$ 1.000\n\t\t\t\t\t,\n\t\t+ R$ \n\t\t1.100 \n\t\tCondomínio\n\t,\n\t\t\t\t\t45 m²\n\t\t\t\t,"\n Moema, São Paulo\n",\n\t\t\t\t\t\t\t\t1 dorm.\n\t\t\t\t\t\t\t,NaN,\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tvaga\n\...,/imobiliarias/aquino-flats_47347267-imoveis.html

#### aluguel
Let's begin cleaning the `aluguel` column. We want it to be a numeric column. At first sight it looks like it contains prices in the form `number` `dot` `number`. Let's see:

In [5]:
pattern_aluguel = r"([0-9]+\.[0-9]+)"
alu = df['aluguel'].str.contains(pattern_aluguel)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/strings.py:1843: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

In [6]:
alu.value_counts()

True     20213
False      523
Name: aluguel, dtype: int64

So, actually, `523` rows do not contain that format. What are they, then?

In [7]:
df['aluguel'][~alu].unique()

array(['\n\t\t\t\t\t\tR$ 900\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 740\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 990\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 998\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 940\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 700\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 950\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 850\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 987\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 790\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 899\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 800\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 960\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 890\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 980\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 860\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 967\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 620\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 974\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 690\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 979\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 865\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 750\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 830\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 750\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 753\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 839\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 766\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 999\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 600\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 870\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 988\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 680\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 780\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 820\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 945\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 869\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 900\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 880\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 825\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 909\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 855\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 860\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 698\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 730\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 500\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 960\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 950\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 760\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 930\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 670\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 650\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 920\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 889\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 850\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 700\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 970\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 669\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 927\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 835\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 829\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 985\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 966\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 875\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 710\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 550\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 578\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 892\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 895\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 951\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 935\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 730\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 728\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 690\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 915\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 940\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 748\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 995\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 765\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 800\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 719\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 840\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 630\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 886\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 695\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 799\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 877\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 924\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 928\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 694\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 910\n\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\tR$ 970\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 841\n\t\t\t\t\t',
       '\n\t\t\t\t\t\tR$ 817\n\t\t\t\t\t'], dtype=object)

Ok, so they are prices below 1000. So the decimal point might or might not be in the pattern we want.

In [8]:
pattern_aluguel2 = r"([0-9]+?\.?[0-9]+)"
alu2 = df['aluguel'].str.contains(pattern_aluguel2)
alu2.value_counts()

True    20736
Name: aluguel, dtype: int64

We caught all possible values of the rent, then. We used capture groups above so that we can use pattern_aluguel2 to extract the string we want:

In [9]:
df['aluguel'] = df['aluguel'].str.extract(pattern_aluguel2)

In [10]:
df['aluguel'] = df['aluguel'].str.replace('.','').astype(float)

In [11]:
df['aluguel']

0        4700.0
1        3720.0
2        3300.0
3        1250.0
4        2835.0
          ...
20731    2100.0
20732    1500.0
20733    2700.0
20734    1000.0
20735    1000.0
Name: aluguel, Length: 20736, dtype: float64

#### condominio
Now we do the same thing for `condominio`

In [12]:
df['condominio'].unique()

array(['\n\t\t+ R$ \n\t\t750 \n\t\tCondomínio\n\t',
       '\n\t\t+ R$ \n\t\t970 \n\t\tCondomínio\n\t',
       '\n\t\t+ R$ \n\t\t443 \n\t\tCondomínio\n\t', ...,
       '\n\t\t+ R$ \n\t\t7.200 \n\t\tCondomínio\n\t',
       '\n\t\t+ R$ \n\t\t98 \n\t\tCondomínio\n\t',
       '\n\t\t+ R$ \n\t\t1.712 \n\t\tCondomínio\n\t'], dtype=object)

In [13]:
pattern_condominio = r"([0-9]?\.?[0-9]+)"
df['condominio'].str.contains(pattern_condominio).value_counts()

True    19355
Name: condominio, dtype: int64

In [14]:
df['condominio'] = df['condominio'].str.extract(pattern_condominio)
df['condominio'] = df['condominio'].str.replace('.','').astype(float)

In [15]:
df['condominio']

0         750.0
1         970.0
2         443.0
3         752.0
4         740.0
          ...
20731    1000.0
20732     700.0
20733     560.0
20734     328.0
20735    1100.0
Name: condominio, Length: 20736, dtype: float64

#### area

In [16]:
df['area'].unique()

array(['\n\t\t\t\t\t82 m²\n\t\t\t\t', '\n\t\t\t\t\t50 m²\n\t\t\t\t',
       '\n\t\t\t\t\t85 m²\n\t\t\t\t', '\n\t\t\t\t\t35 m²\n\t\t\t\t',
       '\n\t\t\t\t\t72 m²\n\t\t\t\t', '\n\t\t\t\t\t45 m²\n\t\t\t\t',
       '\n\t\t\t\t\t67 m²\n\t\t\t\t', '\n\t\t\t\t\t100 m²\n\t\t\t\t',
       '\n\t\t\t\t\t40 m²\n\t\t\t\t', '\n\t\t\t\t\t57 m²\n\t\t\t\t',
       '\n\t\t\t\t\t70 m²\n\t\t\t\t', '\n\t\t\t\t\t118 m²\n\t\t\t\t',
       '\n\t\t\t\t\t55 m²\n\t\t\t\t', '\n\t\t\t\t\t53 m²\n\t\t\t\t',
       '\n\t\t\t\t\t62 m²\n\t\t\t\t', '\n\t\t\t\t\t84 m²\n\t\t\t\t',
       '\n\t\t\t\t\t25 m²\n\t\t\t\t', '\n\t\t\t\t\t200 m²\n\t\t\t\t',
       '\n\t\t\t\t\t71 m²\n\t\t\t\t', '\n\t\t\t\t\t43 m²\n\t\t\t\t',
       '\n\t\t\t\t\t61 m²\n\t\t\t\t', '\n\t\t\t\t\t33 m²\n\t\t\t\t',
       '\n\t\t\t\t\t60 m²\n\t\t\t\t', '\n\t\t\t\t\t127 m²\n\t\t\t\t',
       '\n\t\t\t\t\t90 m²\n\t\t\t\t', '\n\t\t\t\t\t15 m²\n\t\t\t\t',
       '\n\t\t\t\t\t80 m²\n\t\t\t\t', '\n\t\t\t\t\t138 m²\n\t\t\t\t',
       '\n\t\t\t\t\t485 m²\n\t\t\t\t', '\n\t\t\t\t\t133 m²\n\t\t\t\t',
       '\n\t\t\t\t\t32 m²\n\t\t\t\t', '\n\t\t\t\t\t360 m²\n\t\t\t\t',
       '\n\t\t\t\t\t68 m²\n\t\t\t\t', '\n\t\t\t\t\t78 m²\n\t\t\t\t',
       '\n\t\t\t\t\t51 m²\n\t\t\t\t', '\n\t\t\t\t\t54 m²\n\t\t\t\t',
       '\n\t\t\t\t\t130 m²\n\t\t\t\t', '\n\t\t\t\t\t208 m²\n\t\t\t\t',
       '\n\t\t\t\t\t93 m²\n\t\t\t\t', '\n\t\t\t\t\t95 m²\n\t\t\t\t',
       '\n\t\t\t\t\t46 m²\n\t\t\t\t', '\n\t\t\t\t\t37 m²\n\t\t\t\t',
       '\n\t\t\t\t\t165 m²\n\t\t\t\t', '\n\t\t\t\t\t30 m²\n\t\t\t\t',
       '\n\t\t\t\t\t49 m²\n\t\t\t\t', '\n\t\t\t\t\t48 m²\n\t\t\t\t',
       '\n\t\t\t\t\t65 m²\n\t\t\t\t', '\n\t\t\t\t\t125 m²\n\t\t\t\t',
       '\n\t\t\t\t\t42 m²\n\t\t\t\t', '\n\t\t\t\t\t75 m²\n\t\t\t\t',
       '\n\t\t\t\t\t284 m²\n\t\t\t\t', '\n\t\t\t\t\t47 m²\n\t\t\t\t',
       '\n\t\t\t\t\t121 m²\n\t\t\t\t', '\n\t\t\t\t\t710 m²\n\t\t\t\t',
       '\n\t\t\t\t\t185 m²\n\t\t\t\t', '\n\t\t\t\t\t41 m²\n\t\t\t\t',
       '\n\t\t\t\t\t63 m²\n\t\t\t\t', '\n\t\t\t\t\t24 m²\n\t\t\t\t',
       '\n\t\t\t\t\t59 m²\n\t\t\t\t', '\n\t\t\t\t\t150 m²\n\t\t\t\t',
       '\n\t\t\t\t\t26 m²\n\t\t\t\t', '\n\t\t\t\t\t105 m²\n\t\t\t\t',
       '\n\t\t\t\t\t260 m²\n\t\t\t\t', '\n\t\t\t\t\t232 m²\n\t\t\t\t',
       '\n\t\t\t\t\t180 m²\n\t\t\t\t', '\n\t\t\t\t\t258 m²\n\t\t\t\t',
       '\n\t\t\t\t\t16 m²\n\t\t\t\t', '\n\t\t\t\t\t56 m²\n\t\t\t\t',
       '\n\t\t\t\t\t110 m²\n\t\t\t\t', '\n\t\t\t\t\t120 m²\n\t\t\t\t',
       '\n\t\t\t\t\t39 m²\n\t\t\t\t', '\n\t\t\t\t\t34 m²\n\t\t\t\t',
       '\n\t\t\t\t\t310 m²\n\t\t\t\t', '\n\t\t\t\t\t44 m²\n\t\t\t\t',
       '\n\t\t\t\t\t52 m²\n\t\t\t\t', '\n\t\t\t\t\t36 m²\n\t\t\t\t',
       '\n\t\t\t\t\t38 m²\n\t\t\t\t', '\n\t\t\t\t\t116 m²\n\t\t\t\t',
       '\n\t\t\t\t\t23 m²\n\t\t\t\t', '\n\t\t\t\t\t202 m²\n\t\t\t\t',
       '\n\t\t\t\t\t76 m²\n\t\t\t\t', '\n\t\t\t\t\t145 m²\n\t\t\t\t',
       '\n\t\t\t\t\t13 m²\n\t\t\t\t', '\n\t\t\t\t\t27 m²\n\t\t\t\t',
       '\n\t\t\t\t\t64 m²\n\t\t\t\t', '\n\t\t\t\t\t835 m²\n\t\t\t\t',
       '\n\t\t\t\t\t168 m²\n\t\t\t\t', '\n\t\t\t\t\t266 m²\n\t\t\t\t',
       '\n\t\t\t\t\t29 m²\n\t\t\t\t', '\n\t\t\t\t\t74 m²\n\t\t\t\t',
       '\n\t\t\t\t\t58 m²\n\t\t\t\t', '\n\t\t\t\t\t175 m²\n\t\t\t\t',
       '\n\t\t\t\t\t115 m²\n\t\t\t\t', '\n\t\t\t\t\t151 m²\n\t\t\t\t',
       '\n\t\t\t\t\t153 m²\n\t\t\t\t', '\n\t\t\t\t\t28 m²\n\t\t\t\t',
       '\n\t\t\t\t\t87 m²\n\t\t\t\t', '\n\t\t\t\t\t106 m²\n\t\t\t\t',
       '\n\t\t\t\t\t108 m²\n\t\t\t\t', '\n\t\t\t\t\t230 m²\n\t\t\t\t',
       '\n\t\t\t\t\t155 m²\n\t\t\t\t', '\n\t\t\t\t\t236 m²\n\t\t\t\t',
       '\n\t\t\t\t\t220 m²\n\t\t\t\t', '\n\t\t\t\t\t66 m²\n\t\t\t\t',
       '\n\t\t\t\t\t88 m²\n\t\t\t\t', '\n\t\t\t\t\t18 m²\n\t\t\t\t',
       '\n\t\t\t\t\t98 m²\n\t\t\t\t', '\n\t\t\t\t\t92 m²\n\t\t\t\t',
       '\n\t\t\t\t\t73 m²\n\t\t\t\t', '\n\t\t\t\t\t10 m²\n\t\t\t\t',
       '\n\t\t\t\t\t79 m²\n\t\t\t\t', '\n\t\t\t\t\t97 m²\n\t\t\t\t',
       '\n\t\t\t\t\t113 m²\n\t\t\t\t', '\n\t\t\t\t\t124 m²\n\t\t\t\t',
       '\n\t\t\t\t\t94 m²\n\t\t\t\t', '\n\t\t\t\t\t96 m²\n\t\t\t\t',
       '\n\t\t\t\t\t17 m²\n\t\t\t\t', '\n\t\t\t\t\t148 m²\n\t\t\t\t',
       '\n\t\t\t\t\t126 m²\n\t\t\t\t', '\n\t\t\t\t\t190 m²\n\t\t\t\t',
       '\n\t\t\t\t\t136 m²\n\t\t\t\t', '\n\t\t\t\t\t177 m²\n\t\t\t\t',
       '\n\t\t\t\t\t22 m²\n\t\t\t\t', '\n\t\t\t\t\t99 m²\n\t\t\t\t',
       '\n\t\t\t\t\t259 m²\n\t\t\t\t', '\n\t\t\t\t\t20 m²\n\t\t\t\t',
       '\n\t\t\t\t\t69 m²\n\t\t\t\t', '\n\t\t\t\t\t280 m²\n\t\t\t\t',
       '\n\t\t\t\t\t362 m²\n\t\t\t\t', '\n\t\t\t\t\t160 m²\n\t\t\t\t',
       '\n\t\t\t\t\t184 m²\n\t\t\t\t', '\n\t\t\t\t\t210 m²\n\t\t\t\t',
       '\n\t\t\t\t\t117 m²\n\t\t\t\t', '\n\t\t\t\t\t83 m²\n\t\t\t\t',
       '\n\t\t\t\t\t137 m²\n\t\t\t\t', '\n\t\t\t\t\t140 m²\n\t\t\t\t',
       '\n\t\t\t\t\t198 m²\n\t\t\t\t', '\n\t\t\t\t\t787 m²\n\t\t\t\t',
       '\n\t\t\t\t\t500 m²\n\t\t\t\t', '\n\t\t\t\t\t350 m²\n\t\t\t\t',
       '\n\t\t\t\t\t134 m²\n\t\t\t\t', '\n\t\t\t\t\t156 m²\n\t\t\t\t',
       '\n\t\t\t\t\t104 m²\n\t\t\t\t', '\n\t\t\t\t\t207 m²\n\t\t\t\t',
       '\n\t\t\t\t\t31 m²\n\t\t\t\t', '\n\t\t\t\t\t139 m²\n\t\t\t\t',
       '\n\t\t\t\t\t224 m²\n\t\t\t\t', '\n\t\t\t\t\t2800 m²\n\t\t\t\t',
       '\n\t\t\t\t\t86 m²\n\t\t\t\t', '\n\t\t\t\t\t845 m²\n\t\t\t\t',
       '\n\t\t\t\t\t370 m²\n\t\t\t\t', '\n\t\t\t\t\t77 m²\n\t\t\t\t',
       '\n\t\t\t\t\t237 m²\n\t\t\t\t', nan,
       '\n\t\t\t\t\t305 m²\n\t\t\t\t', '\n\t\t\t\t\t142 m²\n\t\t\t\t',
       '\n\t\t\t\t\t161 m²\n\t\t\t\t', '\n\t\t\t\t\t12 m²\n\t\t\t\t',
       '\n\t\t\t\t\t388 m²\n\t\t\t\t', '\n\t\t\t\t\t251 m²\n\t\t\t\t',
       '\n\t\t\t\t\t147 m²\n\t\t\t\t', '\n\t\t\t\t\t154 m²\n\t\t\t\t',
       '\n\t\t\t\t\t123 m²\n\t\t\t\t', '\n\t\t\t\t\t856 m²\n\t\t\t\t',
       '\n\t\t\t\t\t286 m²\n\t\t\t\t', '\n\t\t\t\t\t135 m²\n\t\t\t\t',
       '\n\t\t\t\t\t324 m²\n\t\t\t\t', '\n\t\t\t\t\t182 m²\n\t\t\t\t',
       '\n\t\t\t\t\t261 m²\n\t\t\t\t', '\n\t\t\t\t\t11 m²\n\t\t\t\t',
       '\n\t\t\t\t\t132 m²\n\t\t\t\t', '\n\t\t\t\t\t435 m²\n\t\t\t\t',
       '\n\t\t\t\t\t114 m²\n\t\t\t\t', '\n\t\t\t\t\t272 m²\n\t\t\t\t',
       '\n\t\t\t\t\t268 m²\n\t\t\t\t', '\n\t\t\t\t\t623 m²\n\t\t\t\t',
       '\n\t\t\t\t\t287 m²\n\t\t\t\t', '\n\t\t\t\t\t107 m²\n\t\t\t\t',
       '\n\t\t\t\t\t158 m²\n\t\t\t\t', '\n\t\t\t\t\t21 m²\n\t\t\t\t',
       '\n\t\t\t\t\t290 m²\n\t\t\t\t', '\n\t\t\t\t\t128 m²\n\t\t\t\t',
       '\n\t\t\t\t\t381 m²\n\t\t\t\t', '\n\t\t\t\t\t225 m²\n\t\t\t\t',
       '\n\t\t\t\t\t250 m²\n\t\t\t\t', '\n\t\t\t\t\t340 m²\n\t\t\t\t',
       '\n\t\t\t\t\t81 m²\n\t\t\t\t', '\n\t\t\t\t\t209 m²\n\t\t\t\t',
       '\n\t\t\t\t\t480 m²\n\t\t\t\t', '\n\t\t\t\t\t103 m²\n\t\t\t\t',
       '\n\t\t\t\t\t129 m²\n\t\t\t\t', '\n\t\t\t\t\t172 m²\n\t\t\t\t',
       '\n\t\t\t\t\t269 m²\n\t\t\t\t', '\n\t\t\t\t\t270 m²\n\t\t\t\t',
       '\n\t\t\t\t\t109 m²\n\t\t\t\t', '\n\t\t\t\t\t800 m²\n\t\t\t\t',
       '\n\t\t\t\t\t550 m²\n\t\t\t\t', '\n\t\t\t\t\t131 m²\n\t\t\t\t',
       '\n\t\t\t\t\t91 m²\n\t\t\t\t', '\n\t\t\t\t\t1400 m²\n\t\t\t\t',
       '\n\t\t\t\t\t170 m²\n\t\t\t\t', '\n\t\t\t\t\t400 m²\n\t\t\t\t',
       '\n\t\t\t\t\t343 m²\n\t\t\t\t', '\n\t\t\t\t\t111 m²\n\t\t\t\t',
       '\n\t\t\t\t\t667 m²\n\t\t\t\t', '\n\t\t\t\t\t192 m²\n\t\t\t\t',
       '\n\t\t\t\t\t514 m²\n\t\t\t\t', '\n\t\t\t\t\t311 m²\n\t\t\t\t',
       '\n\t\t\t\t\t475 m²\n\t\t\t\t', '\n\t\t\t\t\t666 m²\n\t\t\t\t',
       '\n\t\t\t\t\t240 m²\n\t\t\t\t', '\n\t\t\t\t\t493 m²\n\t\t\t\t',
       '\n\t\t\t\t\t365 m²\n\t\t\t\t', '\n\t\t\t\t\t243 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1500 m²\n\t\t\t\t', '\n\t\t\t\t\t167 m²\n\t\t\t\t',
       '\n\t\t\t\t\t238 m²\n\t\t\t\t', '\n\t\t\t\t\t119 m²\n\t\t\t\t',
       '\n\t\t\t\t\t430 m²\n\t\t\t\t', '\n\t\t\t\t\t219 m²\n\t\t\t\t',
       '\n\t\t\t\t\t300 m²\n\t\t\t\t', '\n\t\t\t\t\t102 m²\n\t\t\t\t',
       '\n\t\t\t\t\t14 m²\n\t\t\t\t', '\n\t\t\t\t\t596 m²\n\t\t\t\t',
       '\n\t\t\t\t\t89 m²\n\t\t\t\t', '\n\t\t\t\t\t157 m²\n\t\t\t\t',
       '\n\t\t\t\t\t166 m²\n\t\t\t\t', '\n\t\t\t\t\t178 m²\n\t\t\t\t',
       '\n\t\t\t\t\t122 m²\n\t\t\t\t', '\n\t\t\t\t\t169 m²\n\t\t\t\t',
       '\n\t\t\t\t\t101 m²\n\t\t\t\t', '\n\t\t\t\t\t171 m²\n\t\t\t\t',
       '\n\t\t\t\t\t822 m²\n\t\t\t\t', '\n\t\t\t\t\t204 m²\n\t\t\t\t',
       '\n\t\t\t\t\t432 m²\n\t\t\t\t', '\n\t\t\t\t\t635 m²\n\t\t\t\t',
       '\n\t\t\t\t\t275 m²\n\t\t\t\t', '\n\t\t\t\t\t294 m²\n\t\t\t\t',
       '\n\t\t\t\t\t188 m²\n\t\t\t\t', '\n\t\t\t\t\t191 m²\n\t\t\t\t',
       '\n\t\t\t\t\t235 m²\n\t\t\t\t', '\n\t\t\t\t\t335 m²\n\t\t\t\t',
       '\n\t\t\t\t\t195 m²\n\t\t\t\t', '\n\t\t\t\t\t347 m²\n\t\t\t\t',
       '\n\t\t\t\t\t4800 m²\n\t\t\t\t', '\n\t\t\t\t\t228 m²\n\t\t\t\t',
       '\n\t\t\t\t\t256 m²\n\t\t\t\t', '\n\t\t\t\t\t197 m²\n\t\t\t\t',
       '\n\t\t\t\t\t143 m²\n\t\t\t\t', '\n\t\t\t\t\t285 m²\n\t\t\t\t',
       '\n\t\t\t\t\t566 m²\n\t\t\t\t', '\n\t\t\t\t\t213 m²\n\t\t\t\t',
       '\n\t\t\t\t\t149 m²\n\t\t\t\t', '\n\t\t\t\t\t186 m²\n\t\t\t\t',
       '\n\t\t\t\t\t700 m²\n\t\t\t\t', '\n\t\t\t\t\t330 m²\n\t\t\t\t',
       '\n\t\t\t\t\t162 m²\n\t\t\t\t', '\n\t\t\t\t\t420 m²\n\t\t\t\t',
       '\n\t\t\t\t\t405 m²\n\t\t\t\t', '\n\t\t\t\t\t205 m²\n\t\t\t\t',
       '\n\t\t\t\t\t262 m²\n\t\t\t\t', '\n\t\t\t\t\t600 m²\n\t\t\t\t',
       '\n\t\t\t\t\t152 m²\n\t\t\t\t', '\n\t\t\t\t\t540 m²\n\t\t\t\t',
       '\n\t\t\t\t\t146 m²\n\t\t\t\t', '\n\t\t\t\t\t460 m²\n\t\t\t\t',
       '\n\t\t\t\t\t315 m²\n\t\t\t\t', '\n\t\t\t\t\t211 m²\n\t\t\t\t',
       '\n\t\t\t\t\t19 m²\n\t\t\t\t', '\n\t\t\t\t\t249 m²\n\t\t\t\t',
       '\n\t\t\t\t\t390 m²\n\t\t\t\t', '\n\t\t\t\t\t226 m²\n\t\t\t\t',
       '\n\t\t\t\t\t642 m²\n\t\t\t\t', '\n\t\t\t\t\t402 m²\n\t\t\t\t',
       '\n\t\t\t\t\t181 m²\n\t\t\t\t', '\n\t\t\t\t\t196 m²\n\t\t\t\t',
       '\n\t\t\t\t\t144 m²\n\t\t\t\t', '\n\t\t\t\t\t320 m²\n\t\t\t\t',
       '\n\t\t\t\t\t112 m²\n\t\t\t\t', '\n\t\t\t\t\t749 m²\n\t\t\t\t',
       '\n\t\t\t\t\t3000 m²\n\t\t\t\t', '\n\t\t\t\t\t215 m²\n\t\t\t\t',
       '\n\t\t\t\t\t244 m²\n\t\t\t\t', '\n\t\t\t\t\t189 m²\n\t\t\t\t',
       '\n\t\t\t\t\t255 m²\n\t\t\t\t', '\n\t\t\t\t\t248 m²\n\t\t\t\t',
       '\n\t\t\t\t\t821 m²\n\t\t\t\t', '\n\t\t\t\t\t206 m²\n\t\t\t\t',
       '\n\t\t\t\t\t176 m²\n\t\t\t\t', '\n\t\t\t\t\t223 m²\n\t\t\t\t',
       '\n\t\t\t\t\t179 m²\n\t\t\t\t', '\n\t\t\t\t\t163 m²\n\t\t\t\t',
       '\n\t\t\t\t\t7224 m²\n\t\t\t\t', '\n\t\t\t\t\t780 m²\n\t\t\t\t',
       '\n\t\t\t\t\t227 m²\n\t\t\t\t', '\n\t\t\t\t\t1103 m²\n\t\t\t\t',
       '\n\t\t\t\t\t83443 m²\n\t\t\t\t', '\n\t\t\t\t\t440 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1854 m²\n\t\t\t\t', '\n\t\t\t\t\t222 m²\n\t\t\t\t',
       '\n\t\t\t\t\t406 m²\n\t\t\t\t', '\n\t\t\t\t\t387 m²\n\t\t\t\t',
       '\n\t\t\t\t\t463 m²\n\t\t\t\t', '\n\t\t\t\t\t264 m²\n\t\t\t\t',
       '\n\t\t\t\t\t187 m²\n\t\t\t\t', '\n\t\t\t\t\t257 m²\n\t\t\t\t',
       '\n\t\t\t\t\t164 m²\n\t\t\t\t', '\n\t\t\t\t\t252 m²\n\t\t\t\t',
       '\n\t\t\t\t\t193 m²\n\t\t\t\t', '\n\t\t\t\t\t348 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1 m²\n\t\t\t\t', '\n\t\t\t\t\t477 m²\n\t\t\t\t',
       '\n\t\t\t\t\t274 m²\n\t\t\t\t', '\n\t\t\t\t\t520 m²\n\t\t\t\t',
       '\n\t\t\t\t\t505 m²\n\t\t\t\t', '\n\t\t\t\t\t380 m²\n\t\t\t\t',
       '\n\t\t\t\t\t331 m²\n\t\t\t\t', '\n\t\t\t\t\t640 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1200 m²\n\t\t\t\t', '\n\t\t\t\t\t245 m²\n\t\t\t\t',
       '\n\t\t\t\t\t5295 m²\n\t\t\t\t', '\n\t\t\t\t\t506 m²\n\t\t\t\t',
       '\n\t\t\t\t\t760 m²\n\t\t\t\t', '\n\t\t\t\t\t1998 m²\n\t\t\t\t',
       '\n\t\t\t\t\t714 m²\n\t\t\t\t', '\n\t\t\t\t\t1802 m²\n\t\t\t\t',
       '\n\t\t\t\t\t622 m²\n\t\t\t\t', '\n\t\t\t\t\t183 m²\n\t\t\t\t',
       '\n\t\t\t\t\t173 m²\n\t\t\t\t', '\n\t\t\t\t\t317 m²\n\t\t\t\t',
       '\n\t\t\t\t\t246 m²\n\t\t\t\t', '\n\t\t\t\t\t456 m²\n\t\t\t\t',
       '\n\t\t\t\t\t414 m²\n\t\t\t\t', '\n\t\t\t\t\t352 m²\n\t\t\t\t',
       '\n\t\t\t\t\t469 m²\n\t\t\t\t', '\n\t\t\t\t\t332 m²\n\t\t\t\t',
       '\n\t\t\t\t\t641 m²\n\t\t\t\t', '\n\t\t\t\t\t357 m²\n\t\t\t\t',
       '\n\t\t\t\t\t141 m²\n\t\t\t\t', '\n\t\t\t\t\t488 m²\n\t\t\t\t',
       '\n\t\t\t\t\t393 m²\n\t\t\t\t', '\n\t\t\t\t\t809 m²\n\t\t\t\t',
       '\n\t\t\t\t\t356 m²\n\t\t\t\t', '\n\t\t\t\t\t239 m²\n\t\t\t\t',
       '\n\t\t\t\t\t385 m²\n\t\t\t\t', '\n\t\t\t\t\t276 m²\n\t\t\t\t',
       '\n\t\t\t\t\t513 m²\n\t\t\t\t', '\n\t\t\t\t\t747 m²\n\t\t\t\t',
       '\n\t\t\t\t\t254 m²\n\t\t\t\t', '\n\t\t\t\t\t518 m²\n\t\t\t\t',
       '\n\t\t\t\t\t703 m²\n\t\t\t\t', '\n\t\t\t\t\t1002 m²\n\t\t\t\t',
       '\n\t\t\t\t\t174 m²\n\t\t\t\t', '\n\t\t\t\t\t60000 m²\n\t\t\t\t',
       '\n\t\t\t\t\t655 m²\n\t\t\t\t', '\n\t\t\t\t\t368 m²\n\t\t\t\t',
       '\n\t\t\t\t\t660 m²\n\t\t\t\t', '\n\t\t\t\t\t615 m²\n\t\t\t\t',
       '\n\t\t\t\t\t932 m²\n\t\t\t\t', '\n\t\t\t\t\t512 m²\n\t\t\t\t',
       '\n\t\t\t\t\t502 m²\n\t\t\t\t', '\n\t\t\t\t\t630 m²\n\t\t\t\t',
       '\n\t\t\t\t\t489 m²\n\t\t\t\t', '\n\t\t\t\t\t450 m²\n\t\t\t\t',
       '\n\t\t\t\t\t323 m²\n\t\t\t\t', '\n\t\t\t\t\t1000 m²\n\t\t\t\t',
       '\n\t\t\t\t\t859 m²\n\t\t\t\t', '\n\t\t\t\t\t770 m²\n\t\t\t\t',
       '\n\t\t\t\t\t221 m²\n\t\t\t\t', '\n\t\t\t\t\t2500 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1993 m²\n\t\t\t\t', '\n\t\t\t\t\t6700 m²\n\t\t\t\t',
       '\n\t\t\t\t\t850 m²\n\t\t\t\t', '\n\t\t\t\t\t341 m²\n\t\t\t\t',
       '\n\t\t\t\t\t620 m²\n\t\t\t\t', '\n\t\t\t\t\t217 m²\n\t\t\t\t',
       '\n\t\t\t\t\t930 m²\n\t\t\t\t', '\n\t\t\t\t\t295 m²\n\t\t\t\t',
       '\n\t\t\t\t\t241 m²\n\t\t\t\t', '\n\t\t\t\t\t366 m²\n\t\t\t\t',
       '\n\t\t\t\t\t864 m²\n\t\t\t\t', '\n\t\t\t\t\t212 m²\n\t\t\t\t',
       '\n\t\t\t\t\t382 m²\n\t\t\t\t', '\n\t\t\t\t\t314 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1152 m²\n\t\t\t\t', '\n\t\t\t\t\t4500 m²\n\t\t\t\t',
       '\n\t\t\t\t\t815 m²\n\t\t\t\t', '\n\t\t\t\t\t650 m²\n\t\t\t\t',
       '\n\t\t\t\t\t528 m²\n\t\t\t\t', '\n\t\t\t\t\t304 m²\n\t\t\t\t',
       '\n\t\t\t\t\t455 m²\n\t\t\t\t', '\n\t\t\t\t\t1513 m²\n\t\t\t\t',
       '\n\t\t\t\t\t234 m²\n\t\t\t\t', '\n\t\t\t\t\t233 m²\n\t\t\t\t',
       '\n\t\t\t\t\t507 m²\n\t\t\t\t', '\n\t\t\t\t\t4200 m²\n\t\t\t\t',
       '\n\t\t\t\t\t3500 m²\n\t\t\t\t', '\n\t\t\t\t\t425 m²\n\t\t\t\t',
       '\n\t\t\t\t\t218 m²\n\t\t\t\t', '\n\t\t\t\t\t342 m²\n\t\t\t\t',
       '\n\t\t\t\t\t298 m²\n\t\t\t\t', '\n\t\t\t\t\t203 m²\n\t\t\t\t',
       '\n\t\t\t\t\t307 m²\n\t\t\t\t', '\n\t\t\t\t\t273 m²\n\t\t\t\t',
       '\n\t\t\t\t\t333 m²\n\t\t\t\t', '\n\t\t\t\t\t293 m²\n\t\t\t\t',
       '\n\t\t\t\t\t278 m²\n\t\t\t\t', '\n\t\t\t\t\t301 m²\n\t\t\t\t',
       '\n\t\t\t\t\t539 m²\n\t\t\t\t', '\n\t\t\t\t\t412 m²\n\t\t\t\t',
       '\n\t\t\t\t\t296 m²\n\t\t\t\t', '\n\t\t\t\t\t395 m²\n\t\t\t\t',
       '\n\t\t\t\t\t375 m²\n\t\t\t\t', '\n\t\t\t\t\t263 m²\n\t\t\t\t',
       '\n\t\t\t\t\t2000 m²\n\t\t\t\t', '\n\t\t\t\t\t670 m²\n\t\t\t\t',
       '\n\t\t\t\t\t494 m²\n\t\t\t\t', '\n\t\t\t\t\t580 m²\n\t\t\t\t',
       '\n\t\t\t\t\t638 m²\n\t\t\t\t', '\n\t\t\t\t\t2640 m²\n\t\t\t\t',
       '\n\t\t\t\t\t303 m²\n\t\t\t\t', '\n\t\t\t\t\t374 m²\n\t\t\t\t',
       '\n\t\t\t\t\t3590 m²\n\t\t\t\t', '\n\t\t\t\t\t201 m²\n\t\t\t\t',
       '\n\t\t\t\t\t338 m²\n\t\t\t\t', '\n\t\t\t\t\t367 m²\n\t\t\t\t',
       '\n\t\t\t\t\t552 m²\n\t\t\t\t', '\n\t\t\t\t\t389 m²\n\t\t\t\t',
       '\n\t\t\t\t\t424 m²\n\t\t\t\t', '\n\t\t\t\t\t309 m²\n\t\t\t\t',
       '\n\t\t\t\t\t468 m²\n\t\t\t\t', '\n\t\t\t\t\t624 m²\n\t\t\t\t',
       '\n\t\t\t\t\t685 m²\n\t\t\t\t', '\n\t\t\t\t\t532 m²\n\t\t\t\t',
       '\n\t\t\t\t\t265 m²\n\t\t\t\t', '\n\t\t\t\t\t216 m²\n\t\t\t\t',
       '\n\t\t\t\t\t242 m²\n\t\t\t\t', '\n\t\t\t\t\t411 m²\n\t\t\t\t',
       '\n\t\t\t\t\t384 m²\n\t\t\t\t', '\n\t\t\t\t\t1100 m²\n\t\t\t\t',
       '\n\t\t\t\t\t159 m²\n\t\t\t\t', '\n\t\t\t\t\t355 m²\n\t\t\t\t',
       '\n\t\t\t\t\t378 m²\n\t\t\t\t', '\n\t\t\t\t\t364 m²\n\t\t\t\t',
       '\n\t\t\t\t\t306 m²\n\t\t\t\t', '\n\t\t\t\t\t214 m²\n\t\t\t\t',
       '\n\t\t\t\t\t590 m²\n\t\t\t\t', '\n\t\t\t\t\t45002 m²\n\t\t\t\t',
       '\n\t\t\t\t\t474002 m²\n\t\t\t\t', '\n\t\t\t\t\t345 m²\n\t\t\t\t',
       '\n\t\t\t\t\t283 m²\n\t\t\t\t', '\n\t\t\t\t\t410 m²\n\t\t\t\t',
       '\n\t\t\t\t\t417 m²\n\t\t\t\t', '\n\t\t\t\t\t416 m²\n\t\t\t\t',
       '\n\t\t\t\t\t229 m²\n\t\t\t\t', '\n\t\t\t\t\t583 m²\n\t\t\t\t',
       '\n\t\t\t\t\t326 m²\n\t\t\t\t', '\n\t\t\t\t\t253 m²\n\t\t\t\t',
       '\n\t\t\t\t\t351 m²\n\t\t\t\t', '\n\t\t\t\t\t291 m²\n\t\t\t\t',
       '\n\t\t\t\t\t637 m²\n\t\t\t\t', '\n\t\t\t\t\t404 m²\n\t\t\t\t',
       '\n\t\t\t\t\t281 m²\n\t\t\t\t', '\n\t\t\t\t\t2535 m²\n\t\t\t\t',
       '\n\t\t\t\t\t882 m²\n\t\t\t\t', '\n\t\t\t\t\t840 m²\n\t\t\t\t',
       '\n\t\t\t\t\t548 m²\n\t\t\t\t', '\n\t\t\t\t\t715 m²\n\t\t\t\t',
       '\n\t\t\t\t\t594 m²\n\t\t\t\t', '\n\t\t\t\t\t1195 m²\n\t\t\t\t',
       '\n\t\t\t\t\t353 m²\n\t\t\t\t', '\n\t\t\t\t\t593 m²\n\t\t\t\t',
       '\n\t\t\t\t\t730 m²\n\t\t\t\t', '\n\t\t\t\t\t1010 m²\n\t\t\t\t',
       '\n\t\t\t\t\t19300 m²\n\t\t\t\t', '\n\t\t\t\t\t337 m²\n\t\t\t\t',
       '\n\t\t\t\t\t492 m²\n\t\t\t\t', '\n\t\t\t\t\t464 m²\n\t\t\t\t',
       '\n\t\t\t\t\t515 m²\n\t\t\t\t', '\n\t\t\t\t\t750 m²\n\t\t\t\t',
       '\n\t\t\t\t\t329 m²\n\t\t\t\t', '\n\t\t\t\t\t325 m²\n\t\t\t\t',
       '\n\t\t\t\t\t427 m²\n\t\t\t\t', '\n\t\t\t\t\t445 m²\n\t\t\t\t',
       '\n\t\t\t\t\t860 m²\n\t\t\t\t', '\n\t\t\t\t\t1900 m²\n\t\t\t\t',
       '\n\t\t\t\t\t407 m²\n\t\t\t\t', '\n\t\t\t\t\t645 m²\n\t\t\t\t',
       '\n\t\t\t\t\t2696 m²\n\t\t\t\t', '\n\t\t\t\t\t4523 m²\n\t\t\t\t',
       '\n\t\t\t\t\t498 m²\n\t\t\t\t', '\n\t\t\t\t\t826 m²\n\t\t\t\t',
       '\n\t\t\t\t\t462 m²\n\t\t\t\t', '\n\t\t\t\t\t458 m²\n\t\t\t\t',
       '\n\t\t\t\t\t2100 m²\n\t\t\t\t', '\n\t\t\t\t\t6500 m²\n\t\t\t\t',
       '\n\t\t\t\t\t606 m²\n\t\t\t\t', '\n\t\t\t\t\t900 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1350 m²\n\t\t\t\t', '\n\t\t\t\t\t1147 m²\n\t\t\t\t',
       '\n\t\t\t\t\t587 m²\n\t\t\t\t', '\n\t\t\t\t\t386 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1506 m²\n\t\t\t\t', '\n\t\t\t\t\t2861 m²\n\t\t\t\t',
       '\n\t\t\t\t\t839 m²\n\t\t\t\t', '\n\t\t\t\t\t546 m²\n\t\t\t\t',
       '\n\t\t\t\t\t334 m²\n\t\t\t\t', '\n\t\t\t\t\t444 m²\n\t\t\t\t',
       '\n\t\t\t\t\t372 m²\n\t\t\t\t', '\n\t\t\t\t\t346 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1162 m²\n\t\t\t\t', '\n\t\t\t\t\t452 m²\n\t\t\t\t',
       '\n\t\t\t\t\t530 m²\n\t\t\t\t', '\n\t\t\t\t\t20000 m²\n\t\t\t\t',
       '\n\t\t\t\t\t481 m²\n\t\t\t\t', '\n\t\t\t\t\t560 m²\n\t\t\t\t',
       '\n\t\t\t\t\t1680 m²\n\t\t\t\t', '\n\t\t\t\t\t1288 m²\n\t\t\t\t',
       '\n\t\t\t\t\t789 m²\n\t\t\t\t', '\n\t\t\t\t\t271 m²\n\t\t\t\t',
       '\n\t\t\t\t\t443 m²\n\t\t\t\t', '\n\t\t\t\t\t1267 m²\n\t\t\t\t',
       '\n\t\t\t\t\t707 m²\n\t\t\t\t', '\n\t\t\t\t\t584 m²\n\t\t\t\t',
       '\n\t\t\t\t\t474 m²\n\t\t\t\t', '\n\t\t\t\t\t277 m²\n\t\t\t\t',
       '\n\t\t\t\t\t454 m²\n\t\t\t\t', '\n\t\t\t\t\t490 m²\n\t\t\t\t',
       '\n\t\t\t\t\t4000 m²\n\t\t\t\t', '\n\t\t\t\t\t373 m²\n\t\t\t\t',
       '\n\t\t\t\t\t453 m²\n\t\t\t\t', '\n\t\t\t\t\t446 m²\n\t\t\t\t',
       '\n\t\t\t\t\t308 m²\n\t\t\t\t', '\n\t\t\t\t\t17178 m²\n\t\t\t\t',
       '\n\t\t\t\t\t194 m²\n\t\t\t\t', '\n\t\t\t\t\t279 m²\n\t\t\t\t',
       '\n\t\t\t\t\t778 m²\n\t\t\t\t', '\n\t\t\t\t\t247 m²\n\t\t\t\t',
       '\n\t\t\t\t\t748 m²\n\t\t\t\t', '\n\t\t\t\t\t354 m²\n\t\t\t\t',
       '\n\t\t\t\t\t668 m²\n\t\t\t\t', '\n\t\t\t\t\t977 m²\n\t\t\t\t',
       '\n\t\t\t\t\t2300 m²\n\t\t\t\t', '\n\t\t\t\t\t608 m²\n\t\t\t\t',
       '\n\t\t\t\t\t336 m²\n\t\t\t\t', '\n\t\t\t\t\t11300 m²\n\t\t\t\t',
       '\n\t\t\t\t\t11500 m²\n\t\t\t\t', '\n\t\t\t\t\t731 m²\n\t\t\t\t',
       '\n\t\t\t\t\t559 m²\n\t\t\t\t', '\n\t\t\t\t\t1930 m²\n\t\t\t\t',
       '\n\t\t\t\t\t361 m²\n\t\t\t\t', '\n\t\t\t\t\t1750 m²\n\t\t\t\t',
       '\n\t\t\t\t\t535 m²\n\t\t\t\t', '\n\t\t\t\t\t9 m²\n\t\t\t\t',
       '\n\t\t\t\t\t322 m²\n\t\t\t\t', '\n\t\t\t\t\t576 m²\n\t\t\t\t'],
      dtype=object)

In [17]:
pattern_area = r"([0-9]?\.?[0-9]+)"
df['area'].str.contains(pattern_area).value_counts()

True    20640
Name: area, dtype: int64

In [18]:
df['area'] = df['area'].str.extract(pattern_area)
df['area'] = df['area'].str.replace('.','').astype(float)
df['area']

0        82.0
1        50.0
2        85.0
3        35.0
4        72.0
         ...
20731    55.0
20732    45.0
20733    58.0
20734    36.0
20735    45.0
Name: area, Length: 20736, dtype: float64

#### bairro

In [19]:
df['bairro'] = df['bairro'].str.split(',').str[0].str.strip()

In [20]:
df['bairro'].unique()

array(['Chácara Santo Antônio', 'Vila Olímpia', 'Vila das Mercês',
       'Vila Mascote', 'Saúde', 'Bela Vista', 'Vila Mariana',
       'Jardim São Savério', 'Casa Verde', 'Moema', 'Barra Funda',
       'Aclimação', 'Mooca', 'Vila Guarani(Zona Sul)', 'Campo Grande',
       'Vila Andrade', 'Vila Madalena', 'Pinheiros', 'Campo Belo',
       'Perdizes', 'Vila Romana', 'Jardim Aeroporto', 'Vila Matilde',
       'Jardim Paulista', 'Água Branca', 'Brooklin', 'Morumbi',
       'Santo Amaro', 'Vila Nova Conceição', 'Jardim Íris', 'Itaim Bibi',
       'Brás', 'Santana', 'Freguesia do Ó', 'Cerqueira César', 'Butantã',
       'Higienópolis', 'Casa Verde Alta', 'Vila Vera', 'Mandaqui',
       'Tatuapé', 'Jaguaré', 'Cangaíba', 'Jardim Ester Yolanda',
       'Ermelino Matarazzo', 'Santa Cecília', 'Vila São José (Ipiranga)',
       'Panamby', 'Cambuci', 'Parque da Mooca', 'Vila Pompéia',
       'Vila Leopoldina', 'Alto da Boa Vista', 'Jardins', 'Centro',
       'Consolação', 'Vila Regente Feijó', 'Pompéia', 'Bom Retiro',
       'Ponte Rasa', 'Jardim Jussara', 'Chácara Inglesa', 'Jardim Ester',
       'Itaquera', 'Jardim Boa Vista (Zona Oeste)', 'Sapopemba',
       'Vila Campestre', 'Jardim Aricanduva', 'Ipiranga',
       'Cidade São Francisco', 'Interlagos', 'Jabaquara', 'Real Parque',
       'Brooklin Novo', 'Jardim Danfer', 'Lapa', 'Jardim Neide',
       'Jardim Santa Emília', 'Jardim Umuarama', 'Sumaré',
       'Vila Clementino', 'Paraíso', 'Alto da Lapa', 'Liberdade',
       'Jardim Avelino', 'Vila Constança', 'Lauzane Paulista',
       'Vila Califórnia', 'Parque Industrial Tomas Edson', 'Penha',
       'Vila Buarque', 'Paraíso do Morumbi', 'Brooklin Paulista',
       'Vila Carrão', 'Jardim Paulistano', 'Jardim Marajoara',
       'Jardim Anália Franco', 'Vila Dom Pedro I', 'Tucuruvi', 'Piqueri',
       'Artur Alvim', 'Vila São Paulo', 'Jardim Maringá',
       'Vila Uberabinha', 'Granja Julieta', 'Jardim Prudência',
       'Vila Dalila', 'Bosque da Saúde', 'Jardim Europa', 'Pirituba',
       'Belenzinho', 'Vila Sônia', 'Sítio do Mandaqui',
       'Jardim Peri Peri', 'Vila Prudente', 'Vila Amália (Zona Norte)',
       'Vila Cordeiro', 'Chácara Tatuapé', 'Jardim Olympia',
       'Jardim Santa Terezinha (Zona Leste)', 'Vila Ema',
       'Jardim América', 'Vila Nova Cachoeirinha', 'Água Rasa', 'Belém',
       'Campos Elíseos', 'Vila São José (Cidade Dutra)', 'Vila Formosa',
       'Vila Ré', 'Vila Monte Alegre', 'Vila Firmiano Pinto',
       'Vila Maria', 'Conjunto Residencial Ingai', 'Planalto Paulista',
       'Jardim Botucatu', 'Vila Gustavo', 'Vila Butantã',
       'Vila Moinho Velho', 'São Judas', 'Vila Suzana', 'Indianópolis',
       'Vila Pirituba', 'Jardim Guedala', 'Vila Gumercindo',
       'Morro Grande', 'Vila Mangalot', 'Mirandópolis',
       'Jardim Capelinha', 'Vila Alexandria', 'Cidade Monções',
       'Vila Carlos de Campos', 'República', 'Bela Aliança',
       'Sumarezinho', 'Vila Brasílio Machado', 'Vila Mazzei',
       'Jardim Monte Kemel', 'Jardim Helena', 'Cidade Vargas',
       'Alto de Pinheiros', 'Parque Imperial', 'Penha de França',
       'Vila Santa Catarina', 'Parque São Domingos', 'Jardim da Saúde',
       'Vila Ipojuca', 'Canindé', 'Vila Nhocune', 'Vila Talarico',
       'Jardim Nadir', 'Sé', 'Vila Penteado', 'Vila Zelina',
       'Jardim Esmeralda', 'Vila Pirajussara', 'Itaim', 'Vila Centenário',
       'Cidade Ademar', 'Parque Residencial da Lapa', 'Vila Roque',
       'Vila Ede', 'Conceição', 'Veleiros', 'Vila da Saúde',
       'Vila Esperança', 'Vila Gomes Cardim', 'Chácara Califórnia',
       'Jardim Saúde', 'Vila Dionisia', 'Jardim Guairaca', 'Vila Morse',
       'Chácara Klabin', 'Sacomã', 'Catumbi', 'Vila Jacuí',
       'Vila Dom Pedro II', 'Conjunto Habitacional Barreira Grande',
       'Vila Invernada', 'Alto do Ipiranga', 'Água Fria', 'Água Funda',
       'São João Clímaco', 'Parque da Vila Prudente', 'SE',
       'Conjunto Habitacional Juscelino Kubitschek', 'Vila Arapuã',
       'Jardim Ubirajara (Zona Sul)', 'Vila Campo Grande',
       'Jardim das Perdizes', 'Vila Santa Maria', 'Vila Lisboa', 'Imirim',
       'Jardim Londrina', 'Vila do Castelo', 'Jardim Vila Mariana',
       'Morro dos Ingleses', 'Vila Leonor', 'Jardim América da Penha',
       'Jardim Palmares (Zona Sul)', 'Vila São José', 'Vila Amélia',
       'Parque Jabaquara', 'Parque Novo Mundo', 'Vila Nair',
       'Chácara do Encosto', 'Vila Siqueira (Zona Norte)',
       'Vila Santa Clara', 'Vila Rosaria', 'Vila Antonieta',
       'Jardim Brasil (Zona Norte)', 'Jardim da Glória',
       'Cidade Patriarca', 'Vila Diva (Zona Leste)', 'Jardim Bonfiglioli',
       'Chácara Santo Amaro', 'Vila do Encontro', 'Vila Granada',
       'Cidade Líder', 'Jardim Andaraí', 'Vila Independência',
       'Vila Santo Estéfano', 'Santa Teresinha', 'Vila Polopoli',
       'Jardim Santa Maria', 'Várzea da Barra Funda', 'Jardim Ampliação',
       'Vila Santo Estevão', 'Parque Casa de Pedra', 'Vila Maria Alta',
       'Campo Limpo', 'Jardim São Paulo(Zona Norte)', 'Jardim Brasília',
       'Brasilândia', 'São Miguel Paulista', 'Jardim Textil',
       'Chácara Belenzinho', 'Jardim das Bandeiras', 'Jardim Jaqueline',
       'Boaçava', 'Vila Salete', 'Luz', 'Jardim Aurora (Zona Leste)',
       'Nossa Senhora do Ó', 'Vila Cruzeiro', 'Vila Moreira',
       'Vila Sofia', 'Jardim Umarizal', 'Alto da Mooca', 'Socorro',
       'Jardim Vergueiro (Sacomã)', 'Vila Santista',
       'Jardim Independência', 'Vila Prado', 'Ibirapuera',
       'Jardim Parque Morumbi', 'Jardim Leonor', 'Rio Pequeno',
       'Parque dos Príncipes', 'Parque São Lucas', 'Jardim Teresa',
       'Vila Alpina', 'Vila Guilherme', 'Vila Universitária',
       'Vila Aricanduva', 'Jaçanã', 'Jardim Taboão',
       'Parque Bairro Morumbi', 'Vila Monumento', 'Vila Chabilândia',
       'Jardim Arize', 'Vila Romano', 'Jurubatuba', 'Vila Sabrina',
       'Cidade Antônio Estevão de Carvalho', 'Jardim Sul',
       'Jardim Fonte do Morumbi', 'Parque Vitória', 'Jardim Catanduva',
       'Anália Franco', 'Santa Efigênia', 'Jardim Vazani',
       'Vila Nova Savoia', 'Casa Grande', 'Limão', 'Vila Anastácio',
       'Vila Bertioga', 'Vila Nivi', 'Parque Munhoz',
       'Vila São Francisco', 'Itaim Paulista', 'Parque Santa Rita',
       'Chácara Flora', 'Burgo Paulista', 'Vila Parque Jabaquara',
       'Jardim Raposo Tavares', 'Vila Cláudia', 'Parque Mandaqui',
       'Maranhão', 'Jardim Germânia', 'Vila Bela Vista (Zona Sul)',
       'Nova Piraju', 'Jardim Celeste', 'Vila Progredior',
       'Quinta da Paineira', 'Vila Zat', 'Jardim Modelo',
       'Jardim das Acácias', 'Vila Emir', 'Vila Jaraguá',
       'Jardim Promissão', 'Vila Caraguatá', 'Jardim Vila Formosa',
       'Jardim Santa Efigênia', 'Parada Inglesa', 'Vila Medeiros',
       'Carandiru', 'Vila Lageado', 'Guaianazes', 'Pacaembu',
       'Vila São Luís(Zona Oeste)', 'Vila Curuçá', 'City América',
       'Jardim Monjolo', 'Vila Moraes', 'Parque Reboucas',
       'Jardim Taquaral', 'Praça da Árvore', 'Caxingui', 'Vila Ivone',
       'Parque das Árvores', 'Carrão', 'Jardim Alvorada (Zona Oeste)',
       'Jardim das Vertentes', 'Jardim Piracuama', 'Jardim Ibitirama',
       'Vila Gomes', 'Jardim Rio Pequeno', 'Parque Paulistano',
       'Vila Azevedo', 'Vila Araguaia', 'Jardim São Bernardo',
       'Jardim Consórcio', 'Protendit', 'Jardim Popular', 'Jardim Kika',
       'Lapa de Baixo', 'Vila São Francisco (Zona Sul)', 'Vila Bonilha',
       'Jardim Leonor Mendes de Barros', 'Vila Maria Baixa',
       'Jardim Santa Bárbara', 'Jardim Rizzo', 'Vila Indiana',
       'Vila Joaniza', 'Barro Branco (Zona Norte)', 'Vila Beatriz',
       'Jardim Vitória Régia', 'Usina Piratininga', 'Vila Morumbi',
       'Jardim Arpoador', 'Jaraguá', 'Lar São Paulo',
       'Cidade Nova Heliópolis', 'Vila Hamburguesa', 'Jardim Morumbi',
       'Vila Guilhermina', 'Conjunto Promorar Raposo Tavares',
       'Vila Fazzeoni', 'Parque Tomas Saraiva',
       'Jardim São Paulo(Zona Leste)', 'Fazenda Morumbi', 'Vila Paulista',
       'Jardim Cidade Pirituba', 'Vila Santana', 'Jardim Antártica',
       'Jardim Elizabeth', 'Jardim Vera Cruz', 'Vila Euthalia',
       'Vila Paiva', 'Cidade Mãe do Céu', 'Vila Albertina',
       'Vila Babilônia', 'Jardim Felicidade (Zona Oeste)',
       'Conjunto Habitacional Jova Rural', 'Vila Arriete',
       'Conjunto Residencial Butantã', 'Jardim Martins Silva',
       'Chácara Mafalda', 'Vila Jaguara', 'Vila Nova Manchester',
       'Sítio Morro Grande', 'Jardim Vergueiro', 'Jardim Japão',
       'Cidade Jardim', 'Jardim Panorama', 'Jardim Jabaquara',
       'Jardim Maristela', 'Jardim Caboré', 'Várzea de Baixo',
       'Vila Antônio', 'Jardim Luzitânia', 'Americanópolis',
       'Vila Progresso (Zona Leste)', 'Horto', "Jardim D'Abril",
       'Vila Pereira Barreto', 'Vila Bela', 'Jardim Previdência',
       'Super Quadra Morumbi', 'Pari', 'Vila Marieta', 'Parque Ipê',
       'Vila Laís', 'Parque Edu Chaves', 'Parque Colonial',
       'Jardim Ivana', "Cidade D'Abril", 'Jardim do Tiro',
       'Jardim João XXIII', 'Cidade dos Bandeirantes',
       'Jardim Adhemar de Barros', 'Jardim Pinheiros', 'Vila Nova Mazzei',
       'Vila Congonhas', 'Jardim Peri', 'Vila Guarani',
       'Jardim da Campina', 'Vila Guacuri', 'Vila Buenos Aires',
       'Morumbi Sul', 'Jardim Oriental', 'Jardim Lúcia',
       'Vila Aurora (Zona Norte)', 'Jardim Miriam', 'Jardim Marcel',
       'Vila Isa', 'Vila São Silvestre', 'Vila Bonilha Nova',
       'Vila Gertrudes', 'Paraisópolis', 'Vila Gea', 'Vila Heliópolis',
       'Sítio Pinheirinho', 'Jardim Marabá(Zona Sul)',
       'Jardim Brasil (Zona Sul)', 'Loteamento City Jaragua',
       'Jardim Dracena', 'Chácara Santo Antônio (Zona Leste)',
       'Parque Residencial Julia', 'Parque Santa Cecília',
       'Jardim Cupecê', 'Vila Mira', 'Parque Artur Alvim',
       'Jardim São João (Jaraguá)', 'Vila Americana',
       'Jardim das Laranjeiras', 'Jardim São Bento', 'Parque Peruche',
       'Vila Anglo Brasileira', 'Vila do Bosque', 'Vila Prel',
       'Vila dos Remédios', 'Jardim Campo Grande', 'Vila Irmãos Arnoni',
       'Vila Santa Teresa (Zona Sul)', 'Vila Rui Barbosa',
       'Jardim Tremembé', 'Vila Ester', 'Vila Basileia',
       'Parque São Jorge', 'Jardim Colombo'], dtype=object)

#### quartos, banheiros e garagem

In [21]:
df['quartos'].unique()

array(['\n\t\t\t\t\t\t\t\t2 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t1 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t3 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t4 dorm.\n\t\t\t\t\t\t\t', nan,
       '\n\t\t\t\t\t\t\t\t6 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t5 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t7 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t10 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t9 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t145 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t12 dorm.\n\t\t\t\t\t\t\t',
       '\n\t\t\t\t\t\t\t\t11 dorm.\n\t\t\t\t\t\t\t'], dtype=object)

In [22]:
pattern = r"([0-9])"
df['quartos'].str.contains(pattern).value_counts()

True    20512
Name: quartos, dtype: int64

In [23]:
df['quartos'] = df['quartos'].str.extract(pattern)
df['quartos'] = df['quartos'].astype(float)
df['quartos']

0        2.0
1        1.0
2        2.0
3        1.0
4        3.0
        ...
20731    1.0
20732    1.0
20733    2.0
20734    1.0
20735    1.0
Name: quartos, Length: 20736, dtype: float64

In [24]:
df['banheiros'].unique()

array(['\n\t\t\t\t\t2\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t3\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t5\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t4\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       nan,
       '\n\t\t\t\t\t6\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t7\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t8\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t9\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t11\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t10\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t6329\n\t\t\t\t\t\n\t\t\t\t\t\tban\n\t\t\t\t\t\n\t\t\t\t'],
      dtype=object)

In [25]:
df['banheiros'] = df['banheiros'].str.extract(pattern)
df['banheiros'] = df['banheiros'].astype(float)
df['banheiros']

0        2.0
1        1.0
2        2.0
3        1.0
4        2.0
        ...
20731    1.0
20732    1.0
20733    1.0
20734    1.0
20735    NaN
Name: banheiros, Length: 20736, dtype: float64

In [26]:
df['garagem'].unique()

array(['\n\t\t\t\t\t2\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       nan,
       '\n\t\t\t\t\t1\n\t\t\t\t\t\n\t\t\t\t\t\tvaga\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t3\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t5\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t4\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t7\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t6\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t9\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t10\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t12\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t8\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t11\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t14\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t57\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t',
       '\n\t\t\t\t\t87\n\t\t\t\t\t\n\t\t\t\t\t\tvagas\n\t\t\t\t\t\n\t\t\t\t'],
      dtype=object)

In [27]:
df['garagem'] = df['garagem'].str.extract(pattern)
df['garagem'] = df['garagem'].astype(float)
df['garagem']

0        2.0
1        NaN
2        1.0
3        1.0
4        1.0
        ...
20731    1.0
20732    1.0
20733    NaN
20734    NaN
20735    1.0
Name: garagem, Length: 20736, dtype: float64

#### anunciante

In [28]:
df['anunciante'].unique()

array(['/imobiliarias/quintoandar_15743101-imoveis.html',
       '/imobiliarias/strutura-imoveis_15769039-imoveis.html',
       '/imobiliarias/urbano-imoveis_47277001-imoveis.html',
       '/imobiliarias/igor-almeida-real-estate-agency_47031223-imoveis.html',
       '/imobiliarias/imoveis-pro_47370738-imoveis.html',
       '/imobiliarias/kms-associados_15515774-imoveis.html',
       '/imobiliarias/eden-imoveis_15440215-imoveis.html',
       '/imobiliarias/imoveis-varandas_15448780-imoveis.html',
       '/imobiliarias/azera-assessoria-imobiliaria-ltda_30017727-imoveis.html',
       '/imobiliarias/so-flats_47243704-imoveis.html',
       '/imobiliarias/century21-house-prime_15731858-imoveis.html', nan,
       '/imobiliarias/medeiros-negocios-imobiliarios-ltda-me_47008473-imoveis.html',
       '/imobiliarias/scheid-imoveis_47068660-imoveis.html',
       '/imobiliarias/tarcha-imoveis_15458431-imoveis.html',
       '/imobiliarias/broker-vip_47372424-imoveis.html',
       '/imobiliarias/nn-negocios_47248485-imoveis.html',
       '/imobiliarias/sica-consultoria-imobiliaria_15530716-imoveis.html',
       '/imobiliarias/sandra-beatriz-aparecida_47258128-imoveis.html',
       '/imobiliarias/roque-farias-consultoria-de-imoveis_15582384-imoveis.html',
       '/imobiliarias/r2-flats-moema-ii_47026951-imoveis.html',
       '/imobiliarias/romeu-miguel-obeidi-corretor-de-imoveis_15772534-imoveis.html',
       '/imobiliarias/icasaa_super-destaques-e-destaques_47327408-imoveis.html',
       '/imobiliarias/vertiza-imoveis_15744180-imoveis.html',
       '/imobiliarias/new-brokers_15726535-imoveis.html',
       '/imobiliarias/dokter-imoveis_15751725-imoveis.html',
       '/imobiliarias/e7-imoveis-brooklin_47374992-imoveis.html',
       '/imobiliarias/kaazaa-imoveis-unicos_47369646-imoveis.html',
       '/imobiliarias/elh-negocios-imobiliarios-e-empresariais_47311647-imoveis.html',
       '/imobiliarias/guilherme_47329983-imoveis.html',
       '/imobiliarias/aline-grassi_15446409-imoveis.html',
       '/imobiliarias/azular_47295272-imoveis.html',
       '/imobiliarias/local-imoveis-pacaembu_15570895-imoveis.html',
       '/imobiliarias/rgl-imoveis-ltda-me_47158544-imoveis.html',
       '/imobiliarias/lopes-loja-jardins_47024843-imoveis.html',
       '/imobiliarias/fernando-de-moraes_47170131-imoveis.html',
       '/imobiliarias/mais-padrao-imoveis_47254245-imoveis.html',
       '/imobiliarias/organizacao-elo_15579527-imoveis.html',
       '/imobiliarias/conceito-unico-administradora-de-imoveis_47267685-imoveis.html',
       '/imobiliarias/dolores_47399479-imoveis.html',
       '/imobiliarias/espaco-imobiliario_47165960-imoveis.html',
       '/imobiliarias/rf-imoveis_15764502-imoveis.html',
       '/imobiliarias/sh-prime_15772888-imoveis.html',
       '/imobiliarias/viviane-billia_15730804-imoveis.html',
       '/imobiliarias/cirag-boutique-imobiliaria-ltda_30016239-imoveis.html',
       '/imobiliarias/sete-consultoria-imobiliaria_47243438-imoveis.html',
       '/imobiliarias/planescon-consultoria_15551362-imoveis.html',
       '/imobiliarias/sinai-imobiliaria_15456572-imoveis.html',
       '/imobiliarias/zenga-imoveis_47164396-imoveis.html',
       '/imobiliarias/davantage-consultoria-imobiliaria_30004942-imoveis.html',
       '/imobiliarias/ape-27-imobiliaria_47352803-imoveis.html',
       '/imobiliarias/safira-imoveis_15571894-imoveis.html',
       '/imobiliarias/rarus-flats-i_47053969-imoveis.html',
       '/imobiliarias/c2c_47392746-imoveis.html',
       '/imobiliarias/gk-imoveis-pinheiros_47300593-imoveis.html',
       '/imobiliarias/rarus-flats-ii_47152161-imoveis.html',
       '/imobiliarias/ronaldo-farias-negocios-imobiliarios_15460123-imoveis.html',
       '/imobiliarias/maria-borges_47247818-imoveis.html',
       '/imobiliarias/tecnac_15523677-imoveis.html',
       '/imobiliarias/chame-o-corretor_15753447-imoveis.html',
       '/imobiliarias/paulista-flats_15762949-imoveis.html',
       '/imobiliarias/sm-incorporadora-e-vendas_47249524-imoveis.html',
       '/imobiliarias/carrer-elias-consultoria-imobiliaria_15575128-imoveis.html',
       '/imobiliarias/minister-escritorio-tecnico-imobiliario_15553745-imoveis.html',
       '/imobiliarias/assistel-imobiliaria_15437567-imoveis.html',
       '/imobiliarias/ags-imoveis_47152878-imoveis.html',
       '/imobiliarias/assima-assessoria-imoveis-e-administracao-ltda_15515793-imoveis.html',
       '/imobiliarias/tiago-aloi_15764302-imoveis.html',
       '/imobiliarias/silvia-regina-ciaccio-sawaya_15457202-imoveis.html',
       '/imobiliarias/lopes-imoplan_15552701-imoveis.html',
       '/imobiliarias/rodrigues_47078320-imoveis.html',
       '/imobiliarias/de-paula-marques_15760696-imoveis.html',
       '/imobiliarias/vr-flats_15756053-imoveis.html',
       '/imobiliarias/pnielsenmondelo_47375744-imoveis.html',
       '/imobiliarias/famatec-imoveis_47271095-imoveis.html',
       '/imobiliarias/dcn-imoveis_47253426-imoveis.html',
       '/imobiliarias/lello-mooca-locacao_15747850-imoveis.html',
       '/imobiliarias/r2-flats-moema_47152162-imoveis.html',
       '/imobiliarias/avaltec-imoveis_15435655-imoveis.html',
       '/imobiliarias/so-flats-jardins_15444609-imoveis.html',
       '/imobiliarias/dourado-dourado-imoveis-ltda_47292424-imoveis.html',
       '/imobiliarias/the-place-imoveis-integracao_47036504-imoveis.html',
       '/imobiliarias/perrone-imoveis_47062369-imoveis.html',
       '/imobiliarias/lopes-condessa_47052365-imoveis.html',
       '/imobiliarias/mdg-imoveis_47071982-imoveis.html',
       '/imobiliarias/live-here_47242516-imoveis.html',
       '/imobiliarias/vlz-imoveis_47278864-imoveis.html',
       '/imobiliarias/mbigucci_47356060-imoveis.html',
       '/imobiliarias/rutter-negocios-imobiliarios_47259808-imoveis.html',
       '/imobiliarias/leopoldina-house_47379984-imoveis.html',
       '/imobiliarias/claudia-lopes-da-cunha-pereira_47274134-imoveis.html',
       '/imobiliarias/miani-imoveis_15459683-imoveis.html',
       '/imobiliarias/hgb-imoveis_15706588-imoveis.html',
       '/imobiliarias/fanhani-jr.-consultoria_15751148-imoveis.html',
       '/imobiliarias/sell-imoveis_15506275-imoveis.html',
       '/imobiliarias/imobiliaria-camargo-rbc_47380826-imoveis.html',
       '/imobiliarias/inserra_15733037-imoveis.html',
       '/imobiliarias/brookberrini-imoveis_47163412-imoveis.html',
       '/imobiliarias/elohim-imoveis_15452267-imoveis.html',
       '/imobiliarias/hebron-empreendimentos-imobiliarios-ltda_47005095-imoveis.html',
       '/imobiliarias/flavio-ohara_47394822-imoveis.html',
       '/imobiliarias/thais-ventura-imoveis_47354641-imoveis.html',
       '/imobiliarias/lopes-maber_15446359-imoveis.html',
       '/imobiliarias/ciranda-imoveis_15729890-imoveis.html',
       '/imobiliarias/prime-flats_47068817-imoveis.html',
       '/imobiliarias/rofe-imoveis_15588386-imoveis.html',
       '/imobiliarias/claudia-caroline-martins_47075611-imoveis.html',
       '/imobiliarias/ilan-szuster_47355397-imoveis.html',
       '/imobiliarias/lopes-erwin-maack-consultoria-de-imoveis_15550650-imoveis.html',
       '/imobiliarias/adaplan_15529702-imoveis.html',
       '/imobiliarias/goback-imoveis_47295168-imoveis.html',
       '/imobiliarias/castellane-imoveis_15739283-imoveis.html',
       '/imobiliarias/ml-santos-corretora-de-imoveis_47081519-imoveis.html',
       '/imobiliarias/lopes-osasco_47258155-imoveis.html',
       '/imobiliarias/housi_47319958-imoveis.html',
       '/imobiliarias/re-max-complete_47380798-imoveis.html',
       '/imobiliarias/central-invest-imoveis_47237660-imoveis.html',
       '/imobiliarias/re-max-solution_47380812-imoveis.html',
       '/imobiliarias/moraes-reis-imoveis_15564248-imoveis.html',
       '/imobiliarias/barros-corradini_15742234-imoveis.html',
       '/imobiliarias/imobiliaria-anhemby_15457169-imoveis.html',
       '/imobiliarias/longare-venda-locacao-e-adm-de-imoveis-ltda_15548224-imoveis.html',
       '/imobiliarias/castilho-imoveis_15723891-imoveis.html',
       '/imobiliarias/lello-pinheiros-locacao_15748049-imoveis.html',
       '/imobiliarias/europa-brokers-imoveis_47300585-imoveis.html',
       '/imobiliarias/re-max-aliada_47380806-imoveis.html',
       '/imobiliarias/ebano-negocios-e-analises-imobiliarios_15567094-imoveis.html',
       '/imobiliarias/neusa_47285490-imoveis.html',
       '/imobiliarias/vip-consultoria-de-imoveis_15730480-imoveis.html',
       '/imobiliarias/bairro-nobre_30002432-imoveis.html',
       '/imobiliarias/di-palma-campos_15724251-imoveis.html',
       '/imobiliarias/rarus-flats-iii_47054472-imoveis.html',
       '/imobiliarias/ajs-parceria-imoveis_15547686-imoveis.html',
       '/imobiliarias/mm-sales-imoveis_15640562-imoveis.html',
       '/imobiliarias/imobiliaria_-pam_47390713-imoveis.html',
       '/imobiliarias/remax-dream-house_47242070-imoveis.html',
       '/imobiliarias/ellite-flats_47150711-imoveis.html',
       '/imobiliarias/navarro-morales-consultoria-e-negocios-imobiliarios_15440259-imoveis.html',
       '/imobiliarias/conquista-imoveis_15748104-imoveis.html',
       '/imobiliarias/luciana-nuccini_47384006-imoveis.html',
       '/imobiliarias/lavieri-imoveis_15448086-imoveis.html',
       '/imobiliarias/um-imovel_15580669-imoveis.html',
       '/imobiliarias/nova-vida-imoveis_15555983-imoveis.html',
       '/imobiliarias/ramos-francisco_15565617-imoveis.html',
       '/imobiliarias/kramer_15765238-imoveis.html',
       '/imobiliarias/nanci-imoveis_15453917-imoveis.html',
       '/imobiliarias/juscelino-santana_47391831-imoveis.html',
       '/imobiliarias/marcio_47300671-imoveis.html',
       '/imobiliarias/conecta-home_47234112-imoveis.html',
       '/imobiliarias/moria-imoveis_15750298-imoveis.html',
       '/imobiliarias/immobihaus_47241424-imoveis.html',
       '/imobiliarias/marciaasousa_15761501-imoveis.html',
       '/imobiliarias/vendo-casas.net_47039879-imoveis.html',
       '/imobiliarias/imovel-open_47243817-imoveis.html',
       '/imobiliarias/stivim-imoveis_15726286-imoveis.html',
       '/imobiliarias/luiz-falcao_15569394-imoveis.html',
       '/imobiliarias/tc-negocios-imobiliarios_15750934-imoveis.html',
       '/imobiliarias/aquino-flats_47347267-imoveis.html',
       '/imobiliarias/sinale-imoveis_15510771-imoveis.html',
       '/imobiliarias/divcon-imoveis_47241874-imoveis.html',
       '/imobiliarias/liboredo_47073931-imoveis.html',
       '/imobiliarias/sky-realty_15754227-imoveis.html',
       '/imobiliarias/monte-alegre-imoveis_15448381-imoveis.html',
       '/imobiliarias/ib-imobiliaria-bratfisch_15515036-imoveis.html',
       '/imobiliarias/ernani_47315517-imoveis.html',
       '/imobiliarias/rossi-imoveis_15738587-imoveis.html',
       '/imobiliarias/imobiliaria-verthori_47076380-imoveis.html',
       '/imobiliarias/jmfox-negocios-imobiliarios_15723267-imoveis.html',
       '/imobiliarias/rv-consultoria-imobiliaria-especializada_47087543-imoveis.html',
       '/imobiliarias/gdx-consultoria-imobiliaria_15724982-imoveis.html',
       '/imobiliarias/ricardo_47030958-imoveis.html',
       '/imobiliarias/everest-imoveis_15512232-imoveis.html',
       '/imobiliarias/casa-morumbi_47391723-imoveis.html',
       '/imobiliarias/lef-properties_15729455-imoveis.html',
       '/imobiliarias/j-nogueira-imoveis_15457370-imoveis.html',
       '/imobiliarias/lello-norte-locacao_15747858-imoveis.html',
       '/imobiliarias/junior-imoveis_47063183-imoveis.html',
       '/imobiliarias/lopes-morumbi_47233480-imoveis.html',
       '/imobiliarias/grupo-ferreira-imoveis_15746897-imoveis.html',
       '/imobiliarias/paris-condominios_15544938-imoveis.html',
       '/imobiliarias/m.toyota-negocios-imobiliarios_15751105-imoveis.html',
       '/imobiliarias/cys-barreto-assessoria-imobiliaria_47052825-imoveis.html',
       '/imobiliarias/ponto-house-imobiliaria_15765041-imoveis.html',
       '/imobiliarias/re-max-greenhouse_30006069-imoveis.html',
       '/imobiliarias/allflats_47157844-imoveis.html',
       '/imobiliarias/cfr-imoveis_47152564-imoveis.html',
       '/imobiliarias/premium-imoveis_15548567-imoveis.html',
       '/imobiliarias/khondo-assessoria-imobiliaria_15435310-imoveis.html',
       '/imobiliarias/re-max-trio_47380809-imoveis.html',
       '/imobiliarias/oliveira_47315622-imoveis.html',
       '/imobiliarias/imobiliaria-metropolitana_15447536-imoveis.html',
       '/imobiliarias/valor-imoveis_47045843-imoveis.html',
       '/imobiliarias/maxtal-administracao-imoveis-ltda_15455362-imoveis.html',
       '/imobiliarias/hk-imoveis_15725350-imoveis.html',
       '/imobiliarias/hsa-imoveis_47385386-imoveis.html',
       '/imobiliarias/tutoia-imoveis_15513119-imoveis.html',
       '/imobiliarias/gael-imoveis_47253326-imoveis.html',
       '/imobiliarias/escodelar-inteligencia-imobiliaria_30020532-imoveis.html',
       '/imobiliarias/first-consultoria-de-imoveis-ltda._15581067-imoveis.html',
       '/imobiliarias/jb-imovel_47265300-imoveis.html',
       '/imobiliarias/araki-imoveis_15459497-imoveis.html',
       '/imobiliarias/lello-jardins-locacao_15747852-imoveis.html',
       '/imobiliarias/ms-brokers_47087259-imoveis.html',
       '/imobiliarias/loan-gestao-imobiliaria-ltda_15768094-imoveis.html',
       '/imobiliarias/caramelo-imoveis_15515141-imoveis.html',
       '/imobiliarias/hirao-sakamoto_47391978-imoveis.html',
       '/imobiliarias/leuci-imoveis_47166428-imoveis.html',
       '/imobiliarias/lico-imoveis-ltda._47049337-imoveis.html',
       '/imobiliarias/vitoria-flats-negocios-imobiliarios_15522167-imoveis.html',
       '/imobiliarias/century-21-gold_15586025-imoveis.html',
       '/imobiliarias/borghetti-negocios-imobiliarios_15576065-imoveis.html',
       '/imobiliarias/nova-opcao-imoveis_15726385-imoveis.html',
       '/imobiliarias/nova-barao-imoveis_15460125-imoveis.html',
       '/imobiliarias/marcos-vinicius_47040535-imoveis.html',
       '/imobiliarias/di-blasi-assessoria-imobiliaria_15530095-imoveis.html',
       '/imobiliarias/crf-administracao-de-bens_15548188-imoveis.html',
       '/imobiliarias/rose_pinheiro_47399293-imoveis.html',
       '/imobiliarias/gic-gestao-imobiliaria-e-consultoria_47066649-imoveis.html',
       '/imobiliarias/adn-imoveis_15767055-imoveis.html',
       '/imobiliarias/romanucci-imoveis_47063427-imoveis.html',
       '/imobiliarias/remax-studio-76_47282106-imoveis.html',
       '/imobiliarias/smart-brokers_47351964-imoveis.html',
       '/imobiliarias/mario-beltrao-imoveis_15459924-imoveis.html',
       '/imobiliarias/royal-imoveis_15447313-imoveis.html',
       '/imobiliarias/genesis-negocios-imobiliarios_47252120-imoveis.html',
       '/imobiliarias/rooftop-sp_47389925-imoveis.html',
       '/imobiliarias/rarus-flats_47152161-imoveis.html',
       '/imobiliarias/r2-flats_15729569-imoveis.html',
       '/imobiliarias/scano-piva-imoveis-e-administracao-ltda_15438286-imoveis.html',
       '/imobiliarias/imobiliaria-prime-brokers-ltda-me_47011973-imoveis.html',
       '/imobiliarias/ferreira-araujo-corretores-associados-negocios-imobiliarios_15569390-imoveis.html',
       '/imobiliarias/rf-imoveis_47370984-imoveis.html',
       '/imobiliarias/iara-soluc-es-imobiliaria-ldta-me_47008042-imoveis.html',
       '/imobiliarias/marcelo-lopes-consultoria-imobiliaria_47083145-imoveis.html',
       '/imobiliarias/prabitar-imoveis_15543946-imoveis.html',
       '/imobiliarias/dicon-imobiliaria_15439982-imoveis.html',
       '/imobiliarias/samuel-carvalho-imoveis_15448088-imoveis.html',
       '/imobiliarias/leia-graca-ricchetti_30015391-imoveis.html',
       '/imobiliarias/koyama-imoveis_15450081-imoveis.html',
       '/imobiliarias/imoveis-oui_15756094-imoveis.html',
       '/imobiliarias/mestria-imoveis_30009210-imoveis.html',
       '/imobiliarias/sabrina_47299322-imoveis.html',
       '/imobiliarias/paulista-imoveis_15452191-imoveis.html',
       '/imobiliarias/edison-filareto_47169212-imoveis.html',
       '/imobiliarias/valentina-caran-imoveis_15435431-imoveis.html',
       '/imobiliarias/zuccaro-imoveis-creci-27606-j_15725501-imoveis.html',
       '/imobiliarias/itaipu-imoveis_47039895-imoveis.html',
       '/imobiliarias/gofil-imoveis_15772919-imoveis.html',
       '/imobiliarias/imobiliaria-galeao_15756249-imoveis.html',
       '/imobiliarias/imobcom_47011738-imoveis.html',
       '/imobiliarias/imobiliaria-madri-c_47082169-imoveis.html',
       '/imobiliarias/imobiliaria-regiao_15740583-imoveis.html',
       '/imobiliarias/jcbrokers-imobiliaria-e-administracao-de-bens_47031722-imoveis.html',
       '/imobiliarias/imobiliaria-igral_15439644-imoveis.html',
       '/imobiliarias/daniele-elia_47271752-imoveis.html',
       '/imobiliarias/cristovao-chaves-negocios-imobilarios_47171388-imoveis.html',
       '/imobiliarias/madah-imoveis_47021682-imoveis.html',
       '/imobiliarias/robotton-imoveis_15438280-imoveis.html',
       '/imobiliarias/exemplar_47013109-imoveis.html',
       '/imobiliarias/estilo-a_47030845-imoveis.html',
       '/imobiliarias/poggio-imoveis_15565052-imoveis.html',
       '/imobiliarias/sbn-imoveis-ltda-me_30007255-imoveis.html',
       '/imobiliarias/adm-empreendimentos-imobiliarios_47152346-imoveis.html',
       '/imobiliarias/remax-gold-vila-leopoldina_15564738-imoveis.html',
       '/imobiliarias/rosangela_15760279-imoveis.html',
       '/imobiliarias/luiz-carlos-mendes_15503709-imoveis.html',
       '/imobiliarias/vila-mariana-locacao_15751637-imoveis.html',
       '/imobiliarias/baldy-imoveis_47252922-imoveis.html',
       '/imobiliarias/nova-cidade-imoveis_15768381-imoveis.html',
       '/imobiliarias/ramos-imoveis_15435715-imoveis.html',
       '/imobiliarias/n.-carballo-imoveis_15448309-imoveis.html',
       '/imobiliarias/wilson-pepe_15531786-imoveis.html',
       '/imobiliarias/gisele_47372888-imoveis.html',
       '/imobiliarias/fatima_47315629-imoveis.html',
       '/imobiliarias/monte-santo-imobiliaria_47065782-imoveis.html',
       '/imobiliarias/diamante-imoveis_47284170-imoveis.html',
       '/imobiliarias/nova-solar-empreend.-imobil.-s-s-ltda._15532613-imoveis.html',
       '/imobiliarias/carlos-franco-imoveis_15506862-imoveis.html',
       '/imobiliarias/arbo-imoveis_47065316-imoveis.html',
       '/imobiliarias/j.g.-imoveis_15437836-imoveis.html',
       '/imobiliarias/plaka-consultoria-em-imoveis_15451474-imoveis.html',
       '/imobiliarias/tanto-imobiliaria_47027741-imoveis.html',
       '/imobiliarias/perfil-consultoria-imobiliaria_15457785-imoveis.html',
       '/imobiliarias/sandra-carneiro_47353760-imoveis.html',
       '/imobiliarias/brasilio-lopes-imoveis_15766493-imoveis.html',
       '/imobiliarias/imobiliaria-harmonia_15447051-imoveis.html',
       '/imobiliarias/frank-corretor-de-imoveis_47303211-imoveis.html',
       '/imobiliarias/kariane-munhoz_30017014-imoveis.html',
       '/imobiliarias/cristina-bueno-imoveis_47020746-imoveis.html',
       '/imobiliarias/alexandre-pinheiros_47280093-imoveis.html',
       '/imobiliarias/jpl-imoveis_15760811-imoveis.html',
       '/imobiliarias/mar-imoveis_47395562-imoveis.html',
       '/imobiliarias/inova-imob_47335236-imoveis.html',
       '/imobiliarias/orsi-brokers_47147393-imoveis.html',
       '/imobiliarias/rarus-flats-jardins_47054472-imoveis.html',
       '/imobiliarias/beasi-imoveis_15750935-imoveis.html',
       '/imobiliarias/edson-francisco-da-silva_47399832-imoveis.html',
       '/imobiliarias/kc-negocios-imobiliarios_15547853-imoveis.html',
       '/imobiliarias/prohabitar-imoveis_47149151-imoveis.html',
       '/imobiliarias/fms-imoveis_47026858-imoveis.html',
       '/imobiliarias/up-real-estate_47044383-imoveis.html',
       '/imobiliarias/alawara-brasil-gestao-de-condominios-e-imoveis-ltda-me_47026095-imoveis.html',
       '/imobiliarias/willian-casado_47016687-imoveis.html',
       '/imobiliarias/so-flats-imobiliaria_47243703-imoveis.html',
       '/imobiliarias/imobiliaria-paralelo_15453751-imoveis.html',
       '/imobiliarias/pellegrino-imoveis_47240556-imoveis.html',

In [29]:
pattern_anunciante = r"(?<=/imobiliarias/)(.+)(?=_)"

In [30]:
df['anunciante'].str.contains(pattern_anunciante).value_counts()

True    20242
Name: anunciante, dtype: int64

In [31]:
df['anunciante'] = df['anunciante'].str.extract(pattern_anunciante)
df['anunciante']

0                                   quintoandar
1                                   quintoandar
2                                   quintoandar
3                                   quintoandar
4                                   quintoandar
                          ...
20731                              arbo-imoveis
20732                                    kramer
20733                  c.t.sevi-venda-aluga-adm
20734    medeiros-negocios-imobiliarios-ltda-me
20735                              aquino-flats
Name: anunciante, Length: 20736, dtype: object

Now we have a clean dataframe:

In [32]:
df.head()

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
0,4700.0,750.0,82.0,Chácara Santo Antônio,2.0,2.0,2.0,quintoandar
1,3720.0,970.0,50.0,Vila Olímpia,1.0,1.0,NaN,quintoandar
2,3300.0,443.0,85.0,Vila das Mercês,2.0,2.0,1.0,quintoandar
3,1250.0,752.0,35.0,Vila Mascote,1.0,1.0,1.0,quintoandar
4,2835.0,740.0,72.0,Saúde,3.0,2.0,1.0,quintoandar

## Dealing with the `NaN`s

Now that we cleaned our data its time to deal with the missing values.

In [33]:
df.isnull().sum()

aluguel          0
condominio    1381
area            96
bairro           0
quartos        224
banheiros      463
garagem       4287
anunciante     494
dtype: int64

In [34]:
df['garagem'].unique()

array([ 2., nan,  1.,  3.,  5.,  4.,  7.,  6.,  9.,  8.])

We see the column with the most missing values is the garage column. Inspecting its possible values (i.e., the unique values) we see there's no zero in there; but we know some flats for renting don't have any garages.

We also see when there's no garage available the site leaves the spot empty. So the most reasonable Ansatz to fill the missing values here is to fill it with zeros.

In [35]:
df['garagem'].fillna(0, inplace=True)

In [36]:
df.isnull().sum()

aluguel          0
condominio    1381
area            96
bairro           0
quartos        224
banheiros      463
garagem          0
anunciante     494
dtype: int64

In [37]:
df[df['area'].isnull()]

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
620,3930.0,930.0,NaN,Moema,2.0,3.0,1.0,marcio
1021,4300.0,NaN,NaN,Brooklin Novo,1.0,2.0,1.0,vitoria-flats-negocios-imobiliarios
1115,2200.0,420.0,NaN,Jaguaré,2.0,2.0,1.0,mario-beltrao-imoveis
1234,6000.0,NaN,NaN,Chácara Santo Antônio,1.0,1.0,1.0,leia-graca-ricchetti
1532,1000.0,428.0,NaN,Vila Penteado,2.0,1.0,1.0,diamante-imoveis
...,...,...,...,...,...,...,...,...
19121,2006.0,1200.0,NaN,Brooklin,NaN,NaN,0.0,housi
19143,2006.0,1200.0,NaN,Brooklin,NaN,NaN,0.0,housi
19155,2146.0,1297.0,NaN,Vila Olímpia,NaN,NaN,0.0,housi
19836,2500.0,NaN,NaN,Jardim Textil,3.0,1.0,1.0,ags-imoveis
19925,1800.0,838.0,NaN,Vila Olímpia,2.0,2.0,0.0,marcio

One of the key information when renting an apartament is the area it has. Missing area cannot be replaced by some Ansatz (like the mean for like apartaments), because we could have very large apartaments and very small ones in the same building, for example.

And since the missing values are only `.4%` of the total values (vide infra), we'll simply discard these missing rows

In [38]:
len(df[df['area'].isnull()])/len(df['area'])

0.004629629629629629

In [39]:
df.dropna(subset=['area'], inplace=True)

Now let's see the percentage of missing values in each column:

In [40]:
100*df.isnull().sum()/(df.count() + df.isnull().sum())

aluguel       0.000000
condominio    6.545543
area          0.000000
bairro        0.000000
quartos       0.959302
banheiros     2.097868
garagem       0.000000
anunciante    2.393411
dtype: float64

The most alarming missing value here is the condominio. The quartos and banheiros we can drop it -- they're not really expressive.

The anunciante is not really a very important variable, to begin with. So, for now, we'll just leave the missing values from anunciante as they are.

In [41]:
df.dropna(subset=['quartos', 'banheiros'], inplace=True)
100*df.isnull().sum()/(df.count() + df.isnull().sum())

aluguel       0.000000
condominio    6.369077
area          0.000000
bairro        0.000000
quartos       0.000000
banheiros     0.000000
garagem       0.000000
anunciante    2.269327
dtype: float64

Now, to deal with the missing data from condominio we have to note the following: the condominio is set by the building and its related to the services it offers.
Probably a good index for many services in the building is the garage: the more spots there's for a single apartament, probably the steeper the condominio is.

Indeed we see this relationship in the following correlation matrix

In [42]:
df.corr()

             aluguel  condominio      area   quartos  banheiros   garagem
aluguel     1.000000    0.135154 -0.009415  0.223894   0.260540  0.213615
condominio  0.135154    1.000000  0.061756  0.502467   0.656740  0.674347
area       -0.009415    0.061756  1.000000  0.035033   0.038561  0.045013
quartos     0.223894    0.502467  0.035033  1.000000   0.744309  0.631318
banheiros   0.260540    0.656740  0.038561  0.744309   1.000000  0.741554
garagem     0.213615    0.674347  0.045013  0.631318   0.741554  1.000000

To fill the missing values from condominio we'll use the K nearest neighboors algorithm based on the garage:

In [43]:
df_nona = df.copy().dropna()
X_train, X_test, y_train, y_test = train_test_split(np.array(df_nona['garagem']).reshape(-1,1), df_nona['condominio'], random_state = 1)

In [44]:
knn = KNeighborsRegressor(n_neighbors=10)
knn.fit(X_train, y_train)
predictions_test = knn.predict(X_test)
predictions_train = knn.predict(X_train)

Next we'll compare the root mean squared error (RMSE) of the predctions from the train set and the test set to see if we're overfitting.

In [45]:
print(np.sqrt(mean_squared_error(y_test, predictions_test)))
print(np.sqrt(mean_squared_error(y_train, predictions_train)))
print('-'*100)
print(np.std(y_test))

720.7125136839882
727.1420014203217
----------------------------------------------------------------------------------------------------
965.3466892493418

So, we're really not overfitting -- if we were the RMSE from the train set would be much smaller than the one from the test set.

At the same time, the RMSE is smaller than the standard deviation, so its a reasonable estimate. We'll go ahead and use this to fill in the `NaN`s

In [46]:
df[df['condominio'].isnull()]['garagem']

32       0.0
58       1.0
74       0.0
76       1.0
93       1.0
        ...
20605    1.0
20616    0.0
20632    0.0
20701    1.0
20717    1.0
Name: garagem, Length: 1277, dtype: float64

In [47]:
knn = KNeighborsRegressor(n_neighbors=10)
knn.fit(df_nona[['garagem']], df_nona['condominio'])

X_nan = np.array(df[df['condominio'].isnull()]['garagem']).reshape(-1,1)
predictions_nan = knn.predict(X_nan)

Now we'll substitute the missing values for the `predictions_nan`

In [48]:
df[df['condominio'].isnull()]

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
32,1430.0,NaN,15.0,Perdizes,1.0,1.0,0.0,quintoandar
58,4570.0,NaN,35.0,Bela Vista,1.0,1.0,1.0,quintoandar
74,1400.0,NaN,35.0,Vila São José (Ipiranga),1.0,1.0,0.0,icasaa_super-destaques-e-destaques
76,2400.0,NaN,65.0,Morumbi,1.0,1.0,1.0,so-flats
93,3240.0,NaN,41.0,Centro,1.0,1.0,1.0,quintoandar
...,...,...,...,...,...,...,...,...
20605,2900.0,NaN,42.0,Jardins,1.0,1.0,1.0,so-flats
20616,1100.0,NaN,40.0,Mooca,1.0,1.0,0.0,quintoandar
20632,1100.0,NaN,40.0,Mooca,1.0,1.0,0.0,quintoandar
20701,2900.0,NaN,42.0,Jardins,1.0,1.0,1.0,so-flats
20717,2900.0,NaN,42.0,Jardins,1.0,1.0,1.0,so-flats

First we create a pandas series from `predictions_nan` with the same index as the null values from `condominio`:

In [49]:
values_nan = pd.Series(predictions_nan, index=df[df['condominio'].isnull()].index)
values_nan

32       393.3
58       969.1
74       393.3
76       969.1
93       969.1
         ...
20605    969.1
20616    393.3
20632    393.3
20701    969.1
20717    969.1
Length: 1277, dtype: float64

And then we fill the missing values:

In [50]:
df['condominio'].fillna(values_nan, inplace=True)

In [51]:
df['condominio'].isnull().sum()

0

## Making sense of the data

Now, we'll explore the data itself and see if there's anything wrong with the values it contains.

In [52]:
df.describe()

,aluguel,condominio,area,quartos,banheiros,garagem
count,20050.000000,20050.000000,20050.000000,20050.000000,20050.000000,20050.000000
mean,2736.777007,1092.741436,143.111671,1.946633,1.813317,1.212020
std,1819.667976,973.801082,3505.853559,0.952430,1.230529,1.038961
min,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,1582.250000,516.000000,43.000000,1.000000,1.000000,1.000000
50%,2300.000000,831.000000,63.000000,2.000000,1.000000,1.000000
75%,3500.000000,1300.000000,100.000000,3.000000,2.000000,2.000000
max,9990.000000,9990.000000,474002.000000,9.000000,9.000000,9.000000

We already see something weird with the `area`: the minimum value if `1` squared meter. The only reasonable assumption would be if that was an storage unit.

In [53]:
df[df['area'] == 1]

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
4059,2150.0,720.0,1.0,Cambuci,3.0,2.0,2.0,lello-mooca-locacao
4613,5000.0,2061.0,1.0,Vila Olímpia,2.0,3.0,2.0,re-max-400
5833,2000.0,600.0,1.0,Jaçanã,3.0,2.0,1.0,js-cabral-empreendimento-e-comercio-ltda
5890,2300.0,850.0,1.0,Vila Gustavo,3.0,2.0,2.0,js-cabral-empreendimento-e-comercio-ltda
7529,1400.0,600.0,1.0,Vila Nivi,2.0,1.0,1.0,js-cabral-empreendimento-e-comercio-ltda
7576,3000.0,525.0,1.0,Jardim das Bandeiras,2.0,2.0,1.0,rotta-imoveis
9274,2150.0,720.0,1.0,Cambuci,3.0,2.0,2.0,lello-mooca-locacao
9455,1300.0,513.0,1.0,Parque Novo Mundo,2.0,1.0,1.0,tawata-imoveis
9492,2000.0,1456.0,1.0,Vila Mariana,2.0,1.0,1.0,vila-mariana-locacao
10129,2500.0,920.0,1.0,Itaim Bibi,2.0,2.0,0.0,re-max-400
10209,5000.0,2061.0,1.0,Vila Olímpia,2.0,3.0,2.0,re-max-400
10211,8000.0,3414.0,1.0,Paraíso,3.0,3.0,2.0,re-max-400
10829,11.0,940.0,1.0,Itaim Bibi,1.0,1.0,1.0,lello-pinheiros-locacao
11618,2100.0,761.0,1.0,Chácara Klabin,1.0,1.0,1.0,re-max-optima
11865,1000.0,330.0,1.0,Jardim Modelo,2.0,1.0,0.0,js-cabral-empreendimento-e-comercio-ltda
14030,950.0,1.0,1.0,Conjunto Habitacional Jova Rural,2.0,1.0,1.0,js-cabral-empreendimento-e-comercio-ltda
14763,2500.0,1.0,1.0,Vila Gustavo,2.0,2.0,1.0,js-cabral-empreendimento-e-comercio-ltda
15476,1200.0,422.0,1.0,Parque Edu Chaves,2.0,2.0,1.0,js-cabral-empreendimento-e-comercio-ltda
16094,700.0,393.3,1.0,Pirituba,1.0,1.0,0.0,paulo-jose-boltnn-leite
17578,3500.0,969.1,1.0,Jardim Paulista,1.0,1.0,1.0,vitoria-flats-negocios-imobiliarios
18613,1800.0,518.0,1.0,Vila Mariana,1.0,1.0,1.0,locacao
18652,1800.0,518.0,1.0,Vila Mariana,1.0,1.0,1.0,locacao
18653,1850.0,719.0,1.0,Vila Guarani(Zona Sul),3.0,2.0,1.0,locacao
18849,1280.0,745.0,1.0,Vila Mazzei,2.0,2.0,2.0,js-cabral-empreendimento-e-comercio-ltda
19164,2300.0,600.0,1.0,Várzea da Barra Funda,2.0,2.0,1.0,rotta-imoveis
19179,2900.0,750.0,1.0,Perdizes,3.0,3.0,2.0,rotta-imoveis
19270,1800.0,715.0,1.0,Vila Guarani(Zona Sul),2.0,2.0,1.0,locacao
19302,1200.0,1.0,1.0,Vila Dom Pedro II,1.0,1.0,0.0,js-cabral-empreendimento-e-comercio-ltda
19618,1000.0,550.0,1.0,Vila Irmãos Arnoni,2.0,1.0,1.0,js-cabral-empreendimento-e-comercio-ltda
19691,1700.0,1030.0,1.0,Vila Carrão,1.0,2.0,1.0,tawata-imoveis
19716,1700.0,1030.0,1.0,Vila Carrão,1.0,2.0,1.0,tawata-imoveis

There are a bunch of apartaments with area 1 but they're not storage units (they have quartos > 1, they have bathrooms and so on). Their price are also quite high.
With that in mind, this can only be an error.

In [54]:
100*len(df[df['area'] == 1])/len(df)

0.1546134663341646

Since these represent only `.15%` of the total data its best if we simply drop them.

But first let's check if the second least value for area is reasonable (so that we might have hope of not repeatedly dropping absurd values)

In [55]:
criteria = df['area'] == df[df['area'] != 1]['area'].min()
df[criteria]

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
19842,850.0,393.3,9.0,Jardim Bonfiglioli,1.0,1.0,0.0,miani-imoveis

We see its a very small apartament (3x3 m), but with a reasonable price for that size. It makes sense.

So we'll just drop rows with area == 1:

In [56]:
df = df[df['area'] != 1]
df.describe()

,aluguel,condominio,area,quartos,banheiros,garagem
count,20019.000000,20019.000000,20019.000000,20019.000000,20019.000000,20019.000000
mean,2737.613667,1093.163115,143.331735,1.946651,1.813477,1.212148
std,1820.001028,974.147688,3508.562638,0.952751,1.231183,1.039484
min,10.000000,1.000000,9.000000,1.000000,1.000000,0.000000
25%,1590.000000,516.000000,43.000000,1.000000,1.000000,1.000000
50%,2300.000000,831.000000,63.000000,2.000000,1.000000,1.000000
75%,3500.000000,1300.000000,100.000000,3.000000,2.000000,2.000000
max,9990.000000,9990.000000,474002.000000,9.000000,9.000000,9.000000

What about the maximum values for aluguel, condominio and area?

In [57]:
df[df['aluguel'] == df['aluguel'].max()]

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
12647,9990.0,1690.0,320.0,Cidade Monções,3.0,3.0,2.0,lullis-imoveis
15093,9990.0,1690.0,233.0,Cidade Monções,3.0,3.0,2.0,scheid-consultores-de-imoveis
15722,9990.0,1690.0,162.0,Brooklin,3.0,2.0,2.0,every-home

In [58]:
df[df['condominio'] == df['condominio'].max()]

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
15521,75.0,9990.0,1147.0,Vila Nova Conceição,5.0,5.0,5.0,imobiliaria-prime-brokers-ltda-me

In [59]:
df[df['area'] == df['area'].max()]

,aluguel,condominio,area,bairro,quartos,banheiros,garagem,anunciante
13317,22.0,7400.0,474002.0,Paraíso,4.0,5.0,5.0,primeiro-imovel-planejamento-e-consultoria-imo...

The first two are very expensive, but for an initial cleaning we'll leave them as they are.

The row with the maximum area makes less sense.

But we'll leave things as they are, since this is an initial cleaning. A cleaning for analysis and ML (which we do in another notebook) would exclude values above/below some multiple of the Z-score.

Now we'll save this dataframe for further analysis.

In [60]:
df.to_csv('apartamentos_clean.csv', index=False)